### ISSUE TITLE
Add support for the Google VertexAI Embedding API

### ISSUE THREAD

**Issue by tzolov** [spring-projects/spring-ai#1013]
The new [VertexAI Embedding API](https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings) provides Text and Multilingual and Multimodal support.
Implement a corresponding Text EmbeddingModel and explore the possibilities to leverage the multimodal API.

**Comment by dev-jonghoonpark** [comment]
After realising that embedding is not available in gemini, I've been trying to make one since yesterday and you've already started working on it.

Thanks for the awesome work. I hope it gets merged soon.
