### ISSUE TITLE
Qianfan's chatmode returns an error issue due to the presence of system messages in the prompt.

### ISSUE THREAD

**Issue by llggookkokok** [spring-projects/spring-ai#1017]
Use the following code to execute correctly。

org.springframework.ai.qianfan.QianFanChatModel

public ChatCompletionRequest createRequest(Prompt prompt, boolean stream) {
        var chatCompletionMessages = prompt.getInstructions()
                .stream()
                .map(m -> new ChatCompletionMessage(m.getContent(),
                        ChatCompletionMessage.Role.valueOf(m.getMessageType().name())))
                .toList();
        var systemMessageList = chatCompletionMessages.stream().filter(msg -> msg.role() == Role.SYSTEM).toList();
        **var chatMessages = chatCompletionMessages.stream().filter(msg -> msg.role() != Role.SYSTEM).toList();**

......

 var request = new ChatCompletionRequest(chatMessages, systemMessage, stream);

....

**Comment by mxsl-gr** [comment]
hi, i have reproduced the issue and will fix it later. thank you very much for reporting it

**Comment by mxsl-gr** [comment]
fixed in PR https://github.com/spring-projects/spring-ai/pull/1029
