### ISSUE TITLE
Enhance the expansibility of function call

### ISSUE THREAD

**Issue by aRookieMan** [spring-projects/spring-ai#1032]
Spring AI is wonderful, but the form of calling function is not easy to extend. For example, I need to fetch the function calling state and result, send the function name or some thing for user to comfirm. In this case, I have to use my own Function interface, AbstractFunctionCall class and FunctionContext to define, invoke and manager the tool.

Can you make some progress to enhance the expansibility of function call ? plz...

**Comment by tzolov** [comment]
Thank you for the valuable feedback @aRookieMan !

We are considering two (likely exclusive) approaches to handle this: 

1. Optionally, return the message conversation history in the ChatResponse's metadata. E.g. the list of UserMessage, AssistantMessage and TooResponseMessage used in the function call interactions. 
2. After the recent refactoring of our function calling API we will make it possible to disable the automatic/internal function call loops but let the application perform those itself using the plain messages + some provided utility helpers.  This is primary targetted for use cases and applications that want to deliberately shortcut some of the function calling steps (on their own risk).  

What do you think. Would those help your use cases?

**Comment by tzolov** [comment]
@aRookieMan  I believe that https://github.com/spring-projects/spring-ai/commit/501774925c809fb47e02c73688092e46cdb78099 addresses this issue? 
Please, check the [OpenAiChatModelProxyToolCallsIT.java](https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-openai/src/test/java/org/springframework/ai/openai/chat/OpenAiChatModelProxyToolCallsIT.java) for examples how to run the function calling entirely on the client side. 
Let me know if you have further questions.

**Comment by aRookieMan** [comment]
@tzolov Thanks every much, it is helpful. But I have some question:
`new ToolCallHelper.FunctionDefinition("getWeatherInLocation"......)

@Override
		public String call(String functionInput) {
			throw new UnsupportedOperationException(
					"FunctionDefinition provides only metadata. It doesn't implement the call method.");
		}
`
It seems can not be invoked. Is `MethodFunctionCallback` implemented?
