### ISSUE TITLE
Adding new output converters

### ISSUE THREAD

**Issue by urarik** [spring-projects/spring-ai#1036]
**Expected Behavior**

It would be nice that if Spring Ai supports multiple output converter implementations like CSVOutputConverter, YamlOutputConverter and especially XmlOutputConverter.

**Current Behavior**

There is only List,Map,Bean(JSON) Converter.

**Context**

1. If there is some requirements that wants to save a structured output as file and then handle it in business logic, it would be helpful.
2. If someone uses Claude, supporting XmlOutputConverter would be helpful.

I think I can create a pull request for it.

**Comment by urarik** [comment]
@tzolov Hello. I want to contribute this. Can I create a pull request? I'm new to contribute opensource so I mentioned you in this issue.

**Comment by tzolov** [comment]
@urarik I'm not convinced this is required. 
Imo, one can always, and easily, convert the JSON output into any outer format, including CSV or XML. 
This can be as simple as a single line and there are 3rd party tools that can help.

**Comment by urarik** [comment]
@tzolov Thank you for your reply! I just want to contribute this project. So I'm going to find another things to contribute. :)
