### ISSUE TITLE
Misspellings on `spring.io/projects/spring-ai` project page

### ISSUE THREAD

**Issue by jxblum** [spring-projects/spring-ai#1046]
Hi Team-

I apologize in advance for filing this issue ticket here, but I am not really sure where to file issue tickets for spring.io now. I searched the repos under the [spring-io](https://github.com/spring-io) org on GitHub (just in case), but I know we switched to **Contentful** awhile back, and the process to edit project pages changed. Anyway...

On spring.io/projects/spring-ai, there are few mistakes.

First:

<img width="691" alt="Screenshot 2024-07-14 at 10 55 09 PM" src="https://github.com/user-attachments/assets/8a1c4785-9173-4235-b8be-5ed62a4591b5">

Should be: "Mistral AI".

Second:

<img width="996" alt="Screenshot 2024-07-14 at 11 00 33 PM" src="https://github.com/user-attachments/assets/45ff993b-9bf7-4cab-ad1d-8a283c5dc384">

I think this should read: "model", as in "... the Gemini multi-modal **model** just released by Google,..."

Third:

<img width="989" alt="Screenshot 2024-07-14 at 11 04 04 PM" src="https://github.com/user-attachments/assets/1b8c5988-b16c-484e-b3a7-e195d3ce0edd">

I think this would read better as:

"**This command** creates a **new** application for **you** to start basic **interactions** with ChatGPT, ..."

Otherwise, the Spring AI project page reads well and is informative.

Thank you

**Comment by codespearhead** [comment]
Can you give us the link to where we can find those typos? Because it seems that they might have already been fixed.

[1] https://docs.spring.io/spring-ai/reference/getting-started.html#_embeddings_models
[2] I couldn't find it anywhere
[3] https://docs.spring.io/spring-ai/reference/getting-started.html#spring-cli

**Comment by codespearhead** [comment]
I couldn't find either. The data on that page doesn't seem to come from any repository in the [Spring GitHub Organization](https://github.com/spring-projects).

For reference:

[1] https://spring.io/projects/spring-ai#:~:text=Mistal
[2] https://spring.io/projects/spring-ai#:~:text=modal%20modal
[3] https://spring.io/projects/spring-ai#:~:text=for%20your%20to

**Comment by tzolov** [comment]
Hey @jxblum , great to hear from you and glad you keep helping with the project!  
Let me check those Misspellings

**Comment by tzolov** [comment]
> I couldn't find either. The data on that page doesn't seem to come from any repository in the [Spring GitHub Organization](https://github.com/spring-projects).

@codespearhead you are correct, the project's description docs are internal for the Spring team only.

**Comment by tzolov** [comment]
@jxblum I believe i've addressed the mentioned issues: https://spring.io/projects/spring-ai
Also I used the opportunity to update the list of models and vectorstores.

**Comment by jxblum** [comment]
Thank you @tzolov! You are awesome my friend. Changes look great.
