### ISSUE TITLE
Add a DocumentReader implementation for GH Markdown

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-ai#105]
Github Markdown is a popular format that provides ready structural hints as to document content, e.g paragraph, table, etc and many document formats can be converted to markdown, for example pandoc can convert asciidoc to markdown which makes it easier to work with.

I've used https://github.com/commonmark/commonmark-java and the GH extension with success in spring-cli.

**Comment by iAMSagar44** [comment]
Hi @markpollack  - I am unable to use the MardownDocumentReader that was introduced in 1.0.0-M2 Release. 
I tried adding the following dependency and get this error 

> Dependency 'org.springframework.ai:spring-ai-markdown-document-reader:' not found

```
<dependency>
	<groupId>org.springframework.ai</groupId>
	<artifactId>spring-ai-markdown-document-reader</artifactId>
</dependency>
```

The PDF and Tika dependencies work as expected. 

I am using 1.0.0-M2 Spring AI version.

**Comment by ThomasVitale** [comment]
@iAMSagar44 can you try adding the version explicitly to that dependency? (1.0.0-M2)

The new markdown document reader project was not added to the Spring AI BOM, so the version will not be resolved automatically.

Could you also raise a new issue to fix the missing BOM? Thanks!

**Comment by piotrooo** [comment]
It looks like I missed something. I'll try to fix it.
