### ISSUE TITLE
OpenAI Auto Configuration failing to apply Webclient configuration instead of RestClient.

### ISSUE THREAD

**Issue by Adakole2020** [spring-projects/spring-ai#1066]
**Bug description**
The OpenAI autoconfiguration relies on an import of the restclient autoconfiguration or a webclient autoconfiguration. Commit [377b5ff](https://github.com/spring-projects/spring-ai/commit/377b5ffa61427ce94f49793b00f4617edfcc59bc) attempts to fix it but fails to handle the situation when either is null. An `@nullable` annotation on both followed by a later check might be ideal.

<img width="855" alt="Screenshot 2024-07-17 at 2 19 50 PM" src="https://github.com/user-attachments/assets/edb4a3e9-d80a-4cbf-972c-0160782036d1">

**Environment**
Spring-AI: 1.0.0-M1
Java: 21

**Steps to reproduce** 
Initiate chatClient in a reactive setup with no non-reactive dependency inclusions. 
<img width="624" alt="Screenshot 2024-07-17 at 2 19 01 PM" src="https://github.com/user-attachments/assets/cfe52492-b025-4173-a630-ff0e1209bdc8">

**Comment by tzolov** [comment]
Can you please share the complete error stack trace?

**Comment by Adakole2020** [comment]
Does this suffice?
```
Unsatisfied dependency expressed through constructor parameter 0: 
Error creating bean with name 'chatClientBuilder' defined in class path resource [org/springframework/ai/autoconfigure/chat/client/ChatClientAutoConfiguration.class]: Unsatisfied dependency expressed through method 'chatClientBuilder' parameter 1: 
Error creating bean with name 'openAiChatModel' defined in class path resource [org/springframework/ai/autoconfigure/openai/OpenAiAutoConfiguration.class]: Unsatisfied dependency expressed through method 'openAiChatModel' parameter 2: 
No qualifying bean of type 'org.springframework.web.client.RestClient$Builder' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

**Comment by wilkinsona** [comment]
I think this is a bug rather than an enhancement.

The failure occurs when trying to use `spring-boot-starter-webflux`. For example, the following two dependencies will trigger the problem:

```
<dependency>
	<groupId>org.springframework.ai</groupId>
	<artifactId>spring-ai-openai-spring-boot-starter</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-webflux</artifactId>
</dependency>
```

Here's a start.spring.io link that will generate a project that reproduces the problem: https://start.spring.io/#!type=maven-project&language=java&platformVersion=3.3.4&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=spring-ai-with-webflux&name=spring-ai-with-webflux&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.spring-ai-with-webflux&dependencies=spring-ai-openai,webflux.

Generate the project, unzip, and run `./mvnw spring-boot:run`:

```
[INFO] --- spring-boot:3.3.4:run (default-cli) @ spring-ai-with-webflux ---
[INFO] Attaching agents: []

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/

 :: Spring Boot ::                (v3.3.4)

2024-09-23T09:09:50.860+01:00  INFO 48009 --- [spring-ai-with-webflux] [           main] c.e.s.SpringAiWithWebfluxApplication     : Starting SpringAiWithWebfluxApplication using Java 17.0.12 with PID 48009 (/Users/awilkinson/Downloads/spring-ai-with-webflux/target/classes started by awilkinson in /Users/awilkinson/Downloads/spring-ai-with-webflux)
2024-09-23T09:09:50.863+01:00  INFO 48009 --- [spring-ai-with-webflux] [           main] c.e.s.SpringAiWithWebfluxApplication     : No active profile set, falling back to 1 default profile: "default"
2024-09-23T09:09:52.072+01:00  WARN 48009 --- [spring-ai-with-webflux] [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'openAiChatModel' defined in class path resource [org/springframework/ai/autoconfigure/openai/OpenAiAutoConfiguration.class]: Unsatisfied dependency expressed through method 'openAiChatModel' parameter 2: No qualifying bean of type 'org.springframework.web.client.RestClient$Builder' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2024-09-23T09:09:52.081+01:00  INFO 48009 --- [spring-ai-with-webflux] [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-09-23T09:09:52.104+01:00 ERROR 48009 --- [spring-ai-with-webflux] [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 2 of method openAiChatModel in org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration required a bean of type 'org.springframework.web.client.RestClient$Builder' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.web.client.RestClient$Builder' in your configuration.
```

**Comment by axymthr** [comment]
@tzolov Just faced this myself. Is this something only the core team can fix or can anyone submit a patch for it?

**Comment by markpollack** [comment]
related to https://github.com/spring-projects/spring-ai/issues/524

**Comment by wilkinsona** [comment]
I think I'd use a dependency on `spring-web` rather than `spring-boot-starter-web` as I agree that the latter's much to broad in this situation. I'd also update the injection points for `RestClient.Builder` and `WebClient.Builder` to use `ObjectProvider` and only require one or the other (you could guard this with a custom `AnyNestedCondition` that nests classes that are `@ConditionalOnBean(RestClient.Builder.class)` and `@ConditionalOnBean(WebClient.Builder.class)`). That should given you something that works when is building a console app or using `spring-boot-starter-web` or `spring-boot-starter-webflux`.

**Comment by tzolov** [comment]
#1550 should help resolving this issue.

**Comment by fedecompa** [comment]
I can't use spring-ai latest release 1.0.0-M3 with spring.main.web-application-type=reactive. Application failed to start:


Parameter 2 of method openAiEmbeddingModel in org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration required a bean of type 'org.springframework.web.client.RestClient$Builder' that could not be found.

**Comment by tzolov** [comment]
@fedecompa could you please test with 1.0.0-SNAPSHOT well (you will have to add the [snapshot repository](https://docs.spring.io/spring-ai/reference/getting-started.html#repositories) to your pom)? 
Also can you share, which spring boot starers have enabled in your POM?

**Comment by fedecompa** [comment]
@tzolov this is my pom: 

		<spring.ai.bom.version>1.0.0-M3</spring.ai.bom.version>


	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.ai</groupId>
				<artifactId>spring-ai-bom</artifactId>
				<version>${spring.ai.bom.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-openai-spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-pgvector-store-spring-boot-starter</artifactId>
		</dependency>

**Comment by fedecompa** [comment]
@tzolov with the 1.0.0-SNAPSHOT version it works! When will the fix be released? Thanks
