### ISSUE TITLE
Add Redis as a Vector Store

### ISSUE THREAD

**Issue by radhakrishna67** [spring-projects/spring-ai#11]
Current Version of the Spring AI allows InMemoryVectorStore but RedisVectorStore is expected along with.

**Expected Behavior**

Redis should be able to use as VectorStore 

**Current Behavior**

InMemoryVectorStore  is supported.

**Context**

I am working on document querying use-case with azure openai embedding stored in Redis. So i request the team to implement Redis as Vector Store

**Comment by jxblum** [comment]
I am currently investigating using Redis as a `VectorStore` implementation in `spring-ai`.

Here is some [relevant information](https://redis.io/docs/interact/search-and-query/search/vectors/) on the topic that I am currently reading.

**Comment by radhakrishna67** [comment]
@jxblum , I am using Redis for GenAI app. Please let me know if we could connect on this.

**Comment by ankurkumarz** [comment]
I have used Redis as a vector store multiple times with LangChain and considering my Java experience, would like to contribute.

Can it be assigned to me?

**Comment by radhakrishna67** [comment]
@jxblum, any update on Redis VectorStore?

**Comment by jxblum** [comment]
Hi @radhakrishna67 - Thank you for reaching out. 

Sorry for the lapse in communication. I have been juggling multiple responsibilities and haven't been fully allocated/dedicated to working Spring AI just yet. My primary responsibilities are on the Spring Data Team, as the Spring Data Redis technical lead. I have also been busy preparing for Spring Data releases [next week](https://calendar.spring.io/).

I have started crafting a PR for this ticket and hope to have something relatively soon.

Of course, anyone interested in this ticket is also free to experiment, contribute or simply share ideas. Nothing is stopping anyone from doing that.

Anyway, I will report back again when I am ready for some review/feedback.

Cheers!

**Comment by radhakrishna67** [comment]
@jxblum , Thanks for the response. 
I do understand the busy days. I will wait for it.

**Comment by omarmahamid** [comment]
@jxblum 

I'm interested to do some experiment for redis,, 
Is the open ai key is free ? or need billing ?

**Comment by jxblum** [comment]
Hi @omarmahamid - [Creating an OpenAI account](https://platform.openai.com/docs/quickstart/account-setup) at [OpenAI](https://openai.com) and [setting up an API Key](https://platform.openai.com/docs/quickstart/step-2-setup-your-api-key) is free. Once you have signed up and logged in, then you can even add additional keys and organizations to your account.

> NOTE: I have not signed up for Azure OpenAI yet, so I am not familiar with their process.

Of course, not everything is 100% free, and OpenAI will [rate limit](https://platform.openai.com/docs/guides/rate-limits/overview) your requests, naturally.
