### ISSUE TITLE
Querying the number of returned data for a large model

### ISSUE THREAD

**Issue by settven** [spring-projects/spring-ai#1129]
When setting the number of data returned by the query large model, the setting of returning the top does not take effect, and 10 data are returned by default. The calling code is as follows:
List<Document> documents = vectorStore.similaritySearch(SearchRequest.query(keyword).withTopK(48).withSimilarityThreshold(0.1));
The set withTopK number does not take effect

**Comment by settven** [comment]
need help

**Comment by inpink** [comment]
Hello,

It seems like this issue might be related to the one you mentioned. Could you please check it?

Thank you.

https://github.com/spring-projects/spring-ai/issues/1090

**Comment by csterwa** [comment]
@settven please verify that this was resolved with #1090 fix? Please reopen if it is not. Thank you.
