### ISSUE TITLE
redis.clients.jedis.exceptions.JedisDataException: Error parsing vector similarity query: query vector blob size (6144) does not match index's expected size (1536).

### ISSUE THREAD

**Issue by yongheng1065** [spring-projects/spring-ai#1131]
redis.clients.jedis.exceptions.JedisDataException: Error parsing vector similarity query: query vector blob size (6144) does not match index's expected size (1536).  why??

**Comment by bsbodden** [comment]
Because it takes 4 bytes per float and 1536x4=6144 so that size is correct

**Comment by csterwa** [comment]
Please let us know if you have a need for further follow up by reopening. Closing as answered for now @yongheng1065 .
