### ISSUE TITLE
Consider moving `AiResponse` and `Generation` to a separate package from `AiClient`

### ISSUE THREAD

**Issue by jxblum** [spring-projects/spring-ai#120]
The `AiResponse` and `Generation` types are fairly common across different AI providers, AFAICT. Although, where we refer to what the AI returns as a `Generation`, others refer to this as a `Completion`, or based on use, a `Choice`.

Regardless, like `Prompt`, I think that `AiResponse` and `Generation` warrant their own top-level package, such as `org.springframework.ai.generation`, or `org.springframework.ai.response`.

Food for thought.

**Comment by markpollack** [comment]
Great.  Need to view in context of functionality of #108 and #110

**Comment by markpollack** [comment]
BTW, I spent some time thinking about the name of that class, and 'Generation' felt more akin to 'generative ai' than 'completion' as sometimes in other AI models, the completion was completing the next word in a sentence that was passed in.

**Comment by markpollack** [comment]
Closing this as additional detail is captured in https://github.com/spring-projects/spring-ai/issues/241
