### ISSUE TITLE
Introduce batching support for embedding documents

### ISSUE THREAD

**Issue by sobychacko** [spring-projects/spring-ai#1214]
Introduce a way for `EmbeddingModel` implementations to embed `Document` objects using a batching strategy.

**Comment by sobychacko** [comment]
Using this https://github.com/spring-projects/spring-ai/pull/1140 as a starting point, introduce a new API for batching for all vector stores and embedding models to use.

**Comment by impactCn** [comment]
@sobychacko hi, I also encountered the same problem in PG. The segmentation process I use , https://github.com/spring-projects/spring-ai/pull/1200 .
Can you guide me on how to use this batch API?

**Comment by sobychacko** [comment]
@impactCn Sorry for the delay in responding. We just merged similar batching changes for the PG vector store. Can you take a look and see if that satisfies your use case? If there is a gap, we can improve on that. Thanks!
