### ISSUE TITLE
mask_sensitive_info Attribute Missing in MiniMaxChatOptions Class: How to Implement Text Masking?

### ISSUE THREAD

**Issue by znlnzi** [spring-projects/spring-ai#1216]
Issue Description:
The MiniMaxChatOptions class is missing a mask_sensitive_info attribute, which should be used to mask sensitive information in the text. However, this attribute is not currently defined in the class. How should I pass this parameter to achieve text masking functionality?

Steps to Reproduce:

	1.	Attempt to pass the mask_sensitive_info parameter in the MiniMaxChatOptions class.
	2.	Notice that the class does not accept this parameter, making it impossible to mask sensitive information.

Expected Behavior:
It would be helpful to have the mask_sensitive_info attribute added to the MiniMaxChatOptions class, or to be provided with an alternative method to achieve text masking functionality.

Additional Information:
If this attribute should not be added to the MiniMaxChatOptions class, could you please recommend an alternative implementation? Thank you!

**Comment by mxsl-gr** [comment]
hi, @znlnzi 
i checked the document `MiniMax` does have the `mask_sensitive_info` parameter. i will add it later. thank you for reporting this issue

**Comment by mxsl-gr** [comment]
hi, @znlnzi  i have add chat option `mask_sensitive_info` in PR https://github.com/spring-projects/spring-ai/pull/1224

**Comment by znlnzi** [comment]
Thank you for the quick response and for adding the mask_sensitive_info option. I appreciate the update! I’ll check it out and let you know if I run into any further issues.

**Comment by znlnzi** [comment]
> hi, @znlnzi i have add chat option `mask_sensitive_info` in PR #1224您好，@znlnzi 我在 PR #1224 中添加了聊天选项 `mask_sensitive_info` 。

Thank you for the quick response and for adding the mask_sensitive_info option. I appreciate the update! I’ll check it out and let you know if I run into any further issues.
