### ISSUE TITLE
Missing web_search Enum in minimax Tools Type Definition

### ISSUE THREAD

**Issue by znlnzi** [spring-projects/spring-ai#1245]
Issue Description:
The tools attribute in minimax is missing the web_search type in its type definition. This attribute is intended to enable the web search functionality. It would be great if this enumeration could be added to the tools type.

Expected Behavior:
Please add the web_search enum to the tools attribute’s type definition to support the web search feature.

Additional Information:
The inclusion of the web_search option would significantly enhance the usability of the minimax tools by enabling network search capabilities.

**Comment by mxsl-gr** [comment]
hi, @znlnzi 
i checked the document and found the `web_search` attribute, it was quite inconspicuous. i will add it later. thank you for reporting this issue

**Comment by mxsl-gr** [comment]
supported `web_search` on the PR https://github.com/spring-projects/spring-ai/pull/1270
