### ISSUE TITLE
 How to use Google AI Studio’s Gemini API in Spring AI

### ISSUE THREAD

**Issue by losnahj** [spring-projects/spring-ai#1247]
Below are the properties required to use vertexAI.
```
spring.ai.vertex.ai.gemini.project-id=PROJECT_ID
spring.ai.vertex.ai.gemini.location=LOCATION
spring.ai.vertex.ai.gemini.chat.options.model=vertex-pro-vision
spring.ai.vertex.ai.gemini.chat.options.temperature=0.5

#Credential
spring.ai.vertex.ai.gemini.credentialsUri
```
I am using the `Google AI Studio Gemini API` to call LLM just like I am using `OpenAI`.
However, in Google AI Studio, the only thing related to Credential is the API key. How can I use this as Credential?

**Comment by KotlinFactory** [comment]
Really good question also wondering about that. Would be a shame if spring didnt support such an important api. Gemini 1.5pro experimental is currently on top of the LLM-leaderbords.

**Comment by csterwa** [comment]
Closing this as duplicate of #1252
