### ISSUE TITLE
[ChatClient] Allow simple String prompts for convenient onboarding

### ISSUE THREAD

**Issue by ThomasVitale** [spring-projects/spring-ai#1286]
**Expected Behavior**

The `ChatClient` provides a convenient and fluent API. For onboarding/getting-started/education scenarios, it would be nice to make it even more streamlined and allow simple prompts as `String` without the need to know about the concepts of message roles and user messages yet.

Something like this:

```java
var response = chatClient.prompt("What did Gandalf say to the Balrog?")
                         .call()
                         .content();
```

That would be in line with the experience of using the `Prompt` class directly, since it provides a constructor that accepts a `String`:

```java
var prompt = new Prompt("What did Gandalf say to the Balrog?");
```

**Current Behavior**

```java
var response = chatClient.prompt()
                         .user("What did Gandalf say to the Balrog?")
                         .call()
                         .content();
```

**Comment by markpollack** [comment]
I like this.

**Comment by ThomasVitale** [comment]
Nice, thanks for the feedback! I have submitted a PR with the implementation for the suggested improvement> https://github.com/spring-projects/spring-ai/pull/1287
