### ISSUE TITLE
Spring properties not used

### ISSUE THREAD

**Issue by oloyedeolad** [spring-projects/spring-ai#1313]
**Bug description**
The following properties are not being recognized or used in SpringBoot: 
spring.ai.openai.chat.options.response-format.type
spring.ai.openai.chat.options.response-format.name
spring.ai.openai.chat.options.response-format.strict

This leads to error:

org.springframework.ai.retry.NonTransientAiException: 400 - {
  "error": {
    "message": "Missing required parameter: 'response_format.json_schema'.",
    "type": "invalid_request_error",
    "param": "response_format.json_schema",
    "code": "missing_required_parameter"
  }
}

**Environment**
1.0.0-SNAPSHOT

**Steps to reproduce**

- Add the dependency in the pom file following this [documentation](https://docs.spring.io/spring-ai/reference/api/chat/openai-chat.html)
- Add the property to the application.properties
- Make a chat completion call

**Expected behavior**
A response in a structured format.

**Minimal Complete Reproducible example**

<img width="265" alt="image" src="https://github.com/user-attachments/assets/c3406864-13d5-478c-a93e-bf88e92dffb9">
<img width="370" alt="image" src="https://github.com/user-attachments/assets/ec62bfed-bce6-4266-a013-8799d482a231">

**Comment by dmv1167** [comment]
How did you get around this?
