### ISSUE TITLE
Version of spring-ai-spring-boot-docker-compose not managed in BOM

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-ai#1314]
Hey, I noticed that `spring-ai-spring-boot-docker-compose` isn't managed in the BOM. Is this an oversight?

**Comment by iRecursion** [comment]
![artifactId：spring-ai-apache-cassandra-store-spring-boot-starter](https://github.com/user-attachments/assets/d4301d63-b0b9-40f1-a17a-56e0cedf8fea)

**Comment by eddumelendez** [comment]
thanks for the report, @iRecursion . There is another [PR](https://github.com/spring-projects/spring-ai/pull/1312) to fix the dependency for cassandra starter
