### ISSUE TITLE
Tidy up project directory structure

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-ai#132]
The generative AI client implementations are modules sitting at the top of the project, e.g. `spring-ai-ollama`.  Create a directory, `generative-clients` and put the various client modules in that directory

**Comment by Sohardh** [comment]
@markpollack was going to pick this up, just wanted to confirm, i am shifting the following modules to `generative-clients` - 

- spring-ai-azure-openai
- spring-ai-huggingface
- spring-ai-ollama
- spring-ai-openai
- spring-ai-vertex-ai

**Comment by markpollack** [comment]
We have gone with this package structure.  Please comment if you have suggestions.  Closing the issue for now.

```
├── models
│   ├── spring-ai-azure-openai
│   ├── spring-ai-bedrock
│   ├── spring-ai-huggingface
│   ├── spring-ai-ollama
│   ├── spring-ai-openai
│   ├── spring-ai-postgresml
│   ├── spring-ai-transformers
│   └── spring-ai-vertex-ai
```
