### ISSUE TITLE
Do you have a support plan to support qwen2  function call  spring-ai-ollama-spring-boot-starter   ? How long will it take?

### ISSUE THREAD

**Issue by CodingNowPls** [spring-projects/spring-ai#1323]
**Expected Behavior**
  can  support   spring-ai-ollama-spring-boot-starter   use  qwen2   model  function call

**Current Behavior**

 can't support   

**Context**

 i plan to use   spring-ai-ollama-spring-boot-starter   use  qwen2   function call

**Comment by ThomasVitale** [comment]
The Spring AI Ollama integration supports function calling for every model in the Ollama library marked with _Tools_ support. You can find the full list [here](https://ollama.com/search?c=tools). Since the [qwen2](https://ollama.com/library/qwen2) model in Ollama doesn't support tools (you can see the missing "Tools" tag), Spring AI will not either. I would suggest raising a feature request to the Ollama project to make the qwen2 model have tools support.

**Comment by CodingNowPls** [comment]
> The Spring AI Ollama integration supports function calling for every model in the Ollama library marked with _Tools_ support. You can find the full list [here](https://ollama.com/search?c=tools). Since the [qwen2](https://ollama.com/library/qwen2) model in Ollama doesn't support tools (you can see the missing "Tools" tag), Spring AI will not either. I would suggest raising a feature request to the Ollama project to make the qwen2 model have tools support.Spring AI Ollama 集成支持对 Ollama 库中标有_工具_支持的每个模型进行函数调用。您可以[在此处](https://ollama.com/search?c=tools)找到完整列表。由于 Ollama 中的[qwen2](https://ollama.com/library/qwen2)模型不支持工具（您可以看到缺少“Tools”标签），Spring AI 也不支持。我建议向 Ollama 项目提出功能请求，以使 qwen2 模型拥有工具支持。



> The Spring AI Ollama integration supports function calling for every model in the Ollama library marked with _Tools_ support. You can find the full list [here](https://ollama.com/search?c=tools). Since the [qwen2](https://ollama.com/library/qwen2) model in Ollama doesn't support tools (you can see the missing "Tools" tag), Spring AI will not either. I would suggest raising a feature request to the Ollama project to make the qwen2 model have tools support.

Thank you, I will continue to follow up on whether ollama supports qwen2 function call

**Comment by CodingNowPls** [comment]
> The Spring AI Ollama integration supports function calling for every model in the Ollama library marked with _Tools_ support. You can find the full list [here](https://ollama.com/search?c=tools). Since the [qwen2](https://ollama.com/library/qwen2) model in Ollama doesn't support tools (you can see the missing "Tools" tag), Spring AI will not either. I would suggest raising a feature request to the Ollama project to make the qwen2 model have tools support.

Thank you, I will continue to follow up on whether ollama supports qwen2 function call

**Comment by CodingNowPls** [comment]
> Hello @CodingNowPls , please follow up and let us know if the Ollama team will support tools so Spring AI function calling will work with qwen2. We'd like to know if this enhancement is implemented. Thank you.

ok, thank you
