### ISSUE TITLE
JsonReader is not thread safe

### ISSUE THREAD

**Issue by NLxAROSA** [spring-projects/spring-ai#1365]
The code below parellizes the processing across the number of supplied keys. But StringBuilder is not thread-safe. Causes random ArrayIndexOutOfBoundsExceptions in reactive/multi-threaded environments.

https://github.com/spring-projects/spring-ai/blob/5a3521330fae18f48a3c2685d120eddf8db1d0c2/spring-ai-core/src/main/java/org/springframework/ai/reader/JsonReader.java#L95-L99

Most notable with large collections of JSON documents and keys and in reactive environments.

**Comment by tzolov** [comment]
Thanks @NLxAROSA , just caught the same issue. 
The fix is coming shortly.
