### ISSUE TITLE
Latest DJL dependencies cause incompatibility for PyTorch in MacOS x86_64  

### ISSUE THREAD

**Issue by tzolov** [spring-projects/spring-ai#1371]
DJL versions >= 0.29.0 doesn't support PyTorch for MacOS x86_64. 

Additional context: https://github.com/spring-projects/spring-ai/commit/df17f08f5b7c22b31ac73893b90d621180856774#commitcomment-146828827

**Comment by fjtorres** [comment]
Checking DJL documentation, they added a comment about this topic [here](https://djl.ai/engines/pytorch/pytorch-engine/#macos).

**Comment by tzolov** [comment]
Thank you for checking it out.  

Looks like DJL is not going to try to provide some form of backward compatibility for  MacOS x86_64.

The explicit downgrading to `0.28.0` seems to be the only workaround i can think of. Thanks for confirming it works. 
I'm coping it here for are reference. Perhaps we can add it to the Spring Ai docs as well:

```xml
		<dependency>
			<groupId>org.springframework.ai</groupId>
			<artifactId>spring-ai-transformers-spring-boot-starter</artifactId>
			<exclusions>
				<exclusion>
					<groupId>ai.djl.pytorch</groupId>
					<artifactId>pytorch-engine</artifactId>
				</exclusion>
				<exclusion>
					<groupId>ai.djl</groupId>
					<artifactId>api</artifactId>
				</exclusion>
				<exclusion>
					<groupId>ai.djl</groupId>
					<artifactId>model-zoo</artifactId>
				</exclusion>
				<exclusion>
					<groupId>ai.djl.huggingface</groupId>
					<artifactId>tokenizers</artifactId>
				</exclusion>

			</exclusions>
		</dependency>

		<dependency>
			<groupId>ai.djl.pytorch</groupId>
			<artifactId>pytorch-engine</artifactId>
			<version>0.28.0</version>
		</dependency>
		<dependency>
			<groupId>ai.djl</groupId>
			<artifactId>api</artifactId>
			<version>0.28.0</version>
		</dependency>
		<dependency>
			<groupId>ai.djl</groupId>
			<artifactId>model-zoo</artifactId>
			<version>0.28.0</version>
		</dependency>
		<dependency>
			<groupId>ai.djl.huggingface</groupId>
			<artifactId>tokenizers</artifactId>
			<version>0.28.0</version>
		</dependency>
```

**Comment by tzolov** [comment]
Nothing to resolve on Spring AI side. Please use the https://github.com/spring-projects/spring-ai/issues/1371#issuecomment-2358364212 instructions to downgrade the dependencies if neeed.
