### ISSUE TITLE
How to use Spring AI to automatically call HTTP APIs based on natural language descriptions

### ISSUE THREAD

**Issue by OnceCrazyer** [spring-projects/spring-ai#1377]
How to use Spring AI to automatically call HTTP APIs ? I couldn't find any relevant documents.
Perhaps it is possible to support external function calls? For example, JavaScript

**Comment by asaikali** [comment]
Spring Framework provides many methods for making http calls see https://docs.spring.io/spring-framework/reference/integration/rest-clients.html
