### ISSUE TITLE
[Bug] Is there a default AzureOpenAiChatOptions available?

### ISSUE THREAD

**Issue by zhengjian2016** [spring-projects/spring-ai#1414]
About below code:
```java
chatClient = ChatClient.create(chatModel);
chatClient = ChatClient.builder(chatModel).build();
```
It's working for **OpenAiChatModel** and **OllamaChatModel**

Actually, it was working for **AzureOpenAiChatModel** as well before **spring-ai-azure-openai-1.0.0-20240925** , but I'm not sure what date the jar was from. But it isn't working for **AzureOpenAiChatModel** now, due to the following error:
"**responseFormat must not be null**"

It's from the following class:
spring-ai-azure-openai/1.0.0-SNAPSHOT
/spring-ai-azure-openai-1.0.0-**20240925.165056**-619.jar!
/org/springframework/ai/azure/openai/**AzureOpenAiChatOptions.class**
```java
Assert.notNull(responseFormat, "responseFormat must not be null");
```
Is there a default AzureOpenAiChatOptions available?

### Issue Category

- [ ] Enhancement
- [ ] Bug
- [-] Question
- [ ] Documentation gap/issue

### Product Versions
- <spring-boot.version>3.2.5</spring-boot.version>
- <spring-ai.version>1.0.0-SNAPSHOT</spring-ai.version>

### Desired Behavior
Actually, I want to use the default AzureOpenAiChatOptions without having to set them myself, as I don't know how to properly configure them.
I currently don't care about these options, but:
- "Function names must not be null"
- "responseFormat must not be null"
- "logprobs must not be null"
- "topLogprobs must not be null"
- "enhancements must not be null"

Is there a default AzureOpenAiChatOptions available?

### Observed Behavior

I've tried below approach but it's not working:
```java
AzureOpenAiChatOptions.ResponseFormat responseFormat = AzureOpenAiChatOptions.ResponseFormat.TEXT;
AzureOpenAiChatOptions chatOptions = AzureOpenAiChatOptions.builder()
    .withDeploymentName("gpt-4o")
    .withTemperature(0.7)
    .withResponseFormat(responseFormat)
    .build();
```
I got the following error:
"**seed must not be null**"

**Comment by bala-ayalur** [comment]
I faced the same issue and switched back to the 1.0.0-20240919.222959-603 version of spring-ai-azure-openai

**Comment by sobychacko** [comment]
This was a bug and was fixed very recently. Please try the latest snapshots. Thanks!
