### ISSUE TITLE
Add support for GPT-4 with Vision

### ISSUE THREAD

**Issue by ghillert** [spring-projects/spring-ai#144]
Having experimented with OpenAI's `GPT-4 with Vision` API, it would be amazing if Spring AI adds support for image-based input data (e.g. photos). This API allows you to post:

- One or more images
- Images are represented as base64 encoded data or as image URL

The API is located at: API reference: https://platform.openai.com/docs/guides/vision

An implementation could possibly also provide additional pre-processing in order to add support for video data as described here:

https://cookbook.openai.com/examples/gpt_with_vision_for_video_understanding

**Comment by markpollack** [comment]
Pull requests welcome.

**Comment by ghillert** [comment]
It looks like this feature would depend on https://github.com/TheoKanning/openai-java/issues/397

**Comment by markpollack** [comment]
We have moved away from depending on that library and will provide our own implementations.  ATM, brainstorming on having the API incorporate more than just chat models.  Will be able to share a spike branch shortly.  Was just circling back to issues filed wrt to other AI models.  And happy new year Gunnar!

**Comment by arnokoehler** [comment]
How is the spike branch going? Is there a way others could help contribute?

**Comment by Mr-LiuDC** [comment]
Same issue.
Is there any progress?

**Comment by markpollack** [comment]
Closing the issue.  Thanks Thomas, issue pruning has been overdue, working through it now.
