### ISSUE TITLE
How to change the runtime model defaultOptions of ollama here     ,    see getContextChatClient  method

### ISSUE THREAD

**Issue by zjarlin** [spring-projects/spring-ai#1460]
For anything other than bug reports and feature requests (performance, refactoring, etc),
just go ahead and file the issue. Please provide as many details as possible.
<img width="620" alt="图片" src="https://github.com/user-attachments/assets/a41f275b-bb10-4704-8eeb-197927fe8afc">

If you have a question or a support request, please open a new discussion on [GitHub Discussions](https://github.com/spring-projects/spring-ai/discussions)
or ask a question on [StackOverflow](https://stackoverflow.com/questions/tagged/spring-ai).

Please do **not** create issues on the [Issue Tracker](https://github.com/spring-projects/spring-ai/issues) for questions or support requests.
We would like to keep the issue tracker **exclusively** for bug reports and feature requests.

**Comment by zjarlin** [comment]
<img width="620" alt="图片" src="https://github.com/user-attachments/assets/b6441dda-71b3-4238-8c6e-c124759f42a3">
I found that manual switching doesn't work here. It's still the model specified by ollama in yml.

**Comment by ThomasVitale** [comment]
You can configure a model at runtime using the Options API. You can find more information here: https://docs.spring.io/spring-ai/reference/api/chat/ollama-chat.html#chat-options.

Full example with ChatClient and Ollama: https://github.com/ThomasVitale/llm-apps-java-spring-ai/blob/main/01-chat-models/chat-models-ollama/src/main/java/com/thomasvitale/ai/spring/ChatController.java#L43

```java
chatClient
        .prompt("What's the capital of Denmark?")
        .options(ChatOptionsBuilder.builder()
             .withModel("llama3.2")
             .build())
        .call()
        .content();
```

**Comment by zjarlin** [comment]
3q

**Comment by ThomasVitale** [comment]
Yes, here's an example: https://github.com/ThomasVitale/llm-apps-java-spring-ai/blob/main/01-chat-models/chat-models-ollama/src/main/java/com/thomasvitale/ai/spring/model/ChatModelController.java#L40

**Comment by zjarlin** [comment]
<img width="700" alt="图片" src="https://github.com/user-attachments/assets/b958fa20-9bd5-48fe-9658-456270ad8c44">
  /**
         *
        i mean , change the options settings in the model object here🙈

        cannot set this attribute like this:
        ---------------------------------------------------------
        model.defaultOptions = OllamaOptions.builder()
        .withModel(modelName)
        .build()
        -------------------------------------------------
         */
//    how  Change the options property of ChatModel before building the ChatClient instance
