### ISSUE TITLE
The ElasticsearchVectorStoreAutoConfiguration is not public as all the others

### ISSUE THREAD

**Issue by jcgouveia** [spring-projects/spring-ai#1462]
I want to exclude ElasticsearchVectorStoreAutoConfiguration from my spring boot application to define a custom configuration, but the class is not public , therefore I cannot add it to the exclusions list.

All the other VectorStoreAutoConfiguration classes are public.

**Comment by markpollack** [comment]
This has been fixed in https://github.com/spring-projects/spring-ai/commit/b1377d194dc1ebceb7032431b7ac362358a7e82d and will be available in 1.0 M3
