### ISSUE TITLE
Add Support for Cached Tokens in OpenAI Usage Model

### ISSUE THREAD

**Issue by KamilKaletka** [spring-projects/spring-ai#1506]
Hey team,

Could you add support for cached_tokens in the Usage model for OpenAI responses?

The new response structure from OpenAI looks like this:
`"usage": {
  "prompt_tokens": 2006,
  "completion_tokens": 300,
  "total_tokens": 2306,
  "prompt_tokens_details": {
    "cached_tokens": 1920
  },
  "completion_tokens_details": {
    "reasoning_tokens": 0
  }
}`

For more details, you can refer to the official OpenAI documentation on prompt caching:
[OpenAI Prompt Caching Guide](https://platform.openai.com/docs/guides/prompt-caching)

This would be a valuable addition to enhance the accuracy of token usage tracking.

Thanks!

**Comment by abhyudayareddy** [comment]
Submitted PR #5706 which builds on the cached-token support added here to expose token counts (including cached tokens) as Micrometer metrics.

The `FinOpsTokenUsageAdvisor` reads the `Usage` object — including `promptTokens`, `completionTokens`, and `totalTokens` — on every `ChatClient` call and records them as tagged metrics. This makes the data from `prompt_tokens_details.cached_tokens` visible in Actuator/Prometheus dashboards without any call-site changes.
