### ISSUE TITLE
Milvus vector stores expects a boolean instead of a store config

### ISSUE THREAD

**Issue by Stevan1996** [spring-projects/spring-ai#1552]
**Bug description**
According to [this documentation](https://docs.spring.io/spring-ai/docs/current/api/org/springframework/ai/vectorstore/MilvusVectorStore.html), the `MilvusVectorStore` expects a `MilvusVectoreStoreConfig` as third parameter. However, the IDE tells me that the third parameter is a boolean called  `initializeSchema`. Is the documentation outdated? If so, how can I manually configure the Milvus vector store.

**Environment**
Spring AI version `1.0.0-M3`

**Steps to reproduce**
```kotlin
@Bean 
fun vectorStore(milvusClient: MilvusServiceClient, embeddingModel: EmbeddingModel): VectorStore {
    val config = MilvusVectorStoreConfig.builder()
          .withCollectionName("foo")
          .withDatabaseName("bar")
          .withMetricType(MetricType.COSINE)
          .build()
    return MilvusVectorStore(milvusClient, embeddingModel, config)
}
```
This should result in a type mismatch error for the third parameter.

**Expected behavior**
The constructor signature should match the documented signature.

**Comment by ilayaperumalg** [comment]
Hi @Stevan1996, The JavaDoc documentations for both SNAPSHOT and M3 are now fixed and published [here](https://spring.io/projects/spring-ai#learn).
