### ISSUE TITLE
In Anthropic 3 API, Response body is not showing in stacktrace if ChatModel.stream() fails

### ISSUE THREAD

**Issue by jombidev** [spring-projects/spring-ai#1583]
### **Bug description**
on call of `AnthropicChatModel.stream` (method signature: `org.springframework.ai.anthropic.AnthropicChatModel#stream(Lorg/springframework/ai/chat/prompt/Prompt;)Lreactor/core/publisher/Flux;`), thrown exception's response body is not displaying correctly.
<img width="1460" alt="Screenshot 2024-10-22 at 14 31 39" src="https://github.com/user-attachments/assets/1ab684bd-9d03-49d0-9f10-adaed8d1f6b1">

At the AnthropicApi#110, `ClientResponse#bodyToMono` is never used as Publisher. I don't think it's intentional. It should display the body of error request, instead of `Mono<T>#toString()`.
<img width="780" alt="Screenshot 2024-10-22 at 14 05 28" src="https://github.com/user-attachments/assets/38849418-a9e2-49d6-a37b-6e23ef7f07b7">

### **Environment**
Amazon Corretto 17 (OpenJDK 17)
Spring Boot - 3.3.0
Spring AI - 1.0.0-M3

### **Minimal Complete Reproducible example**
Here is simple java code to reproduce:
```java
AnthropicApi api = new AnthropicApi("LEAVING_IT_EMPTY");
StreamingChatModel model = new AnthropicChatModel(api, new AnthropicChatOptions());

model.stream(new Prompt("Hello, world!"))
        .doOnEach((res) -> System.out.println(res.get()))
        .blockLast();
```
<img width="1406" alt="Screenshot 2024-10-22 at 14 51 05" src="https://github.com/user-attachments/assets/57ff8f39-a13f-41bd-8e4f-7b72f7c4d956">

### **Expected behavior**
It can be displayed by passing WebClient builder in constructor of `AnthropicApi`, but it should display at default.
Await the mono variable. we can get body as String properly.
<img width="1451" alt="Screenshot 2024-10-22 at 14 58 23" src="https://github.com/user-attachments/assets/2e7679a8-5670-48e2-985e-8c311838efe2">

changing ``Mono.just~~`` to below code:
```java
resp
.bodyToMono(java.lang.String.class)
.map((body) -> new RuntimeException("Response exception, Status: [" + resp.statusCode() +
                  "], Body:[" + body + "]"))
```
Will work as expected.

**Comment by DHKIM-0511** [comment]
Fix PR https://github.com/spring-projects/spring-ai/pull/1721

**Comment by markpollack** [comment]
Sorry, we should have closed this issue last Friday, the fix already in main and was part of this commit 9fa89a2fd65dba03bd27b26ac49fd32a9fab558a

**Comment by jombidev** [comment]
I have confirmed that the issue has been resolved, but written commit log is not correct.
here is the fixed commit: https://github.com/spring-projects/spring-ai/commit/fb2e7528d0b74ae4adcb4aa6e18436bff2e808e5
