### ISSUE TITLE
please don't transitively bring in `spring-boot-starter-webflux`

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-ai#162]
in `spring-ai-openai`, please consider using:

```xml
<dependency>
  <groupId>io.projectreactor</groupId>
  <artifactId>reactor-core</artifactId>
</dependency>
```

instead of 

```xml
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-webflux</artifactId>
</dependency>
````

otherwise folks who consume that dependency will pull in a full blown web stack which will start a web server, which they may not want or need.

**Comment by tzolov** [comment]
Thanks @joshlong , resolved at 1f3aedac060f6861025f62f2e4111bafbd1d183b
