### ISSUE TITLE
ChromaDB vector store port configuration doesn't register

### ISSUE THREAD

**Issue by kevintanhongann** [spring-projects/spring-ai#1715]
ChromaDB port configuration doesn't register properly even though the application yml configuration was correct.

**Bug description**
![image](https://github.com/user-attachments/assets/65dfc65f-9e1f-488b-8845-53d352f62c53)

Error shows when the app is run
`Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "localhost:/api/v1/collections/vector_store": unknown protocol: localhost`

**Environment**
Spring AI version 1.0.0-SNAPSHOT, Java 11, using Chroma vector store

**Expected behavior**
Port number should be appended properly to connect to the chromadb.

**Comment by eddumelendez** [comment]
host should be http://localhost instead

**Comment by tzolov** [comment]
I've fixed the documentation to point to the correct default host property: https://docs.spring.io/spring-ai/reference/api/vectordbs/chroma.html#_configuration_properties

**Comment by kevintanhongann** [comment]
Awesome thanks 👍
