### ISSUE TITLE
Add support for Google Gemini

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-ai#179]
Now that it is out ;) we can add support.

https://glaforge.medium.com/get-started-with-gemini-in-java-923f2069ea4d is a nice starter

**Comment by King-Chau** [comment]
should we add Gemini to spring-ai-vertex-ai module or a new module?

**Comment by King-Chau** [comment]
@markpollack #189 please review, thx

**Comment by knightcube** [comment]
I was just about to raise this issue. Good to see that it is already being worked on🙂

**Comment by tzolov** [comment]
Resolved with 65d42c9d4fb4a434a6c262747a86a2af1e82e05e
