### ISSUE TITLE
Fix the aggregation of tokens in metrics taking into account function calls

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-ai#1800]
This was done for Amazon Bedrock Converse but needs to be done for the other all the other models.
- [x] AnthropicChatModel : https://github.com/spring-projects/spring-ai/pull/1918
- [x] AzureOpenAiChatModel : https://github.com/spring-projects/spring-ai/pull/1916
- [x] BedrockProxyChatModel : https://github.com/spring-projects/spring-ai/issues/1743
- [x] OpenAiChatModel : https://github.com/spring-projects/spring-ai/pull/1872
- [x] MiniMaxChatModel : **TBD**: https://github.com/spring-projects/spring-ai/issues/1980
- [x] MistralAiChatModel : https://github.com/spring-projects/spring-ai/pull/1905
- [x] MoonshotChatModel : https://github.com/spring-projects/spring-ai/pull/1927
- [x] OllamaChatModel  : https://github.com/spring-projects/spring-ai/pull/1848
- [x] VertexAiGeminiChatModel: **TBD** https://github.com/spring-projects/spring-ai/pull/1963 & https://github.com/spring-projects/spring-ai/issues/1992
- [x] ZhiPuAiChatModel **TBD**: https://github.com/spring-projects/spring-ai/issues/1979

**Comment by ilayaperumalg** [comment]
Mark this as complete and moving the TBD PR/issues into the upcoming release.
