### ISSUE TITLE
ZhipuAI FunctionCalling Error 

### ISSUE THREAD

**Issue by jiao-duan** [spring-projects/spring-ai#1828]
**Bug description**
When integrating SpringAI with Zhipu AI to perform function calls, serialization issues occur. Upon inspection, it is found that the serialization configuration in the FunctionTool class of the ZhiPuAiApi is problematic.

**Environment**
use version is 1.0.0-SNAPSHOT 
<img width="493" alt="image" src="https://github.com/user-attachments/assets/a95da752-2227-43c9-8382-59dd0bd2dc61">
![image](https://github.com/user-attachments/assets/4e5333ab-1096-48b9-a329-b4b5e6b04613)

**Comment by jiao-duan** [comment]
Bug error page is:
![image](https://github.com/user-attachments/assets/bf57e624-99c8-4752-9191-8dd4127e35e6)

**Comment by jiao-duan** [comment]
when i modify the FunctionTool class, it's run succuess
![image](https://github.com/user-attachments/assets/82e1fa5d-f865-4397-afd8-d069d16f5c39)

**Comment by mxsl-gr** [comment]
I checked the file history and found that it was mistakenly modified in commit [3e9a3fd3b0bb508a07ee7aff5526f35e841b077c](https://github.com/spring-projects/spring-ai/commit/3e9a3fd3b0bb508a07ee7aff5526f35e841b077c).

**Comment by jiao-duan** [comment]
I am glad that you can find this mistake and fix it

**Comment by ilayaperumalg** [comment]
Fixed via https://github.com/spring-projects/spring-ai/pull/1829. Thanks @jiao-duan and @mxsl-gr!
