### ISSUE TITLE
Update Documentation: I hope the changes in the M4 version (Advisors and Modular RAG) can be updated in the documentation.

### ISSUE THREAD

**Issue by kevintsai1202** [spring-projects/spring-ai#1850]
The M4 version of Advisors has undergone many changes, and the RAG section now includes Modular RAG. However, the documentation has not been updated. I hope the changes in the M4 version can be reflected in the documentation.

**Comment by ThomasVitale** [comment]
I'm working on this. Though, please notice that the Modular RAG features in the M4 release are still experimental and available as preview. Some of the APIs might still change before we land on the final design. That's also why we haven't included documentation yet.
