### ISSUE TITLE
Put builder class inside PortableFunctionCallingOptions

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-ai#1874]
Currently the FunctionCallingOptionsBuilder is a separate class, it should be removed and instead a 'standard spring-ai' builder pattern be used inside PortableFunctionCallingOptions.

'standard spring-ai' builder at the moment is

* no 'with' prefix on methods
* check for passing in null values
* for a 'simple' case like options, where there aren't going to be multiple implementations, there isn't a need for a builder interface.

Also rename PortableFunctionCallingOptions to DefaultFunctionCallingOptions

**Comment by ilayaperumalg** [comment]
This is addressed via https://github.com/spring-projects/spring-ai/commit/b25d6e8d2d7ab1acdda2362aee1b4ff882892f13
