### ISSUE TITLE
Merge oopsie in README.md

### ISSUE THREAD

**Issue by larrydiamond** [spring-projects/spring-ai#196]
Please do a quick search on GitHub issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
Accidental chevrons from merge left in README.md

**Environment**
Just in README.md file - does not affect runtime

**Steps to reproduce**
Just in README.md file - does not affect runtime

**Expected behavior**
Just in README.md file - does not affect runtime

**Minimal Complete Reproducible example**
Just in README.md file - does not affect runtime

**Comment by larrydiamond** [comment]
https://github.com/spring-projects/spring-ai/pull/197 will resolve this issue.

**Comment by markpollack** [comment]
Merged, and thanks!
