### ISSUE TITLE
RedisVectorStore is broken?

### ISSUE THREAD

**Issue by shannonantony** [spring-projects/spring-ai#1990]
Please do a quick search on GitHub issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
In the SNAPSHOT release, looks like RedisVectorStore class is broken.

protected RedisVectorStore(RedisBuilder builder) {
		super(builder);

		Assert.notNull(builder.jedis, "JedisPooled must not be null");

		this.jedis = builder.jedis;
		this.indexName = builder.indexName;
		this.prefix = builder.prefix;
		this.contentFieldName = builder.contentFieldName;
		this.embeddingFieldName = builder.embeddingFieldName;
		this.vectorAlgorithm = builder.vectorAlgorithm;
		this.metadataFields = builder.metadataFields;
		this.initializeSchema = builder.initializeSchema;
		this.batchingStrategy = builder.batchingStrategy;
		this.filterExpressionConverter = new RedisFilterExpressionConverter(this.metadataFields);
	}

How do I wire the EmbeddingModel in RedisVectorStore?

**Comment by ThomasVitale** [comment]
Recently, a new Builder API has been implemented for `RedisVectorStore`. You can instantiate a new instance and pass an `EmbeddingModel` as follows:

`RedisVectorStore vectorStore = RedisVectorStore.builder(jedis, embeddingModel).build();`

**Comment by shannonantony** [comment]
Can you help me which new Builder API you're referring to . I can't find a reference to implement

RedisVectorStore vectorStore = RedisVectorStore.builder(jedis, embeddingModel).build();

Aappreciate if you could provide a sample code snippet

thanks
Jay

**Comment by markpollack** [comment]
Hi.  The previous constructors have been deprecated, so existing code will work, if that isn't the case please post what isn't working.

The ref docs are in the process of being updated, should be done for the release today.

In the meantime, you can look at [this configuration](https://github.com/spring-projects/spring-ai/blob/6477c0ccfc028c0bf62858ed9b53dd0196bc8241/vector-stores/spring-ai-redis-store/src/test/java/org/springframework/ai/vectorstore/redis/RedisVectorStoreIT.java#L265) used in the integration tests.

**Comment by shannonantony** [comment]
Thank you very much !!! @markpollack
