### ISSUE TITLE
Typo in Azure OpenAI documentation

### ISSUE THREAD

**Issue by rai-sandeep** [spring-projects/spring-ai#236]
The Getting Started heading has a typo in [Azure OpenAI](https://docs.spring.io/spring-ai/reference/api/clients/azure-openai.html) section of the docs.

<img width="722" alt="image" src="https://github.com/spring-projects/spring-ai/assets/36532643/22e107ce-91bc-43f7-834e-6d87e64901c1">

**Comment by rai-sandeep** [comment]
I submitted a pull request to fix this issue: https://github.com/spring-projects/spring-ai/pull/237

**Comment by markpollack** [comment]
Thanks, will review and merge shortly.
