### ISSUE TITLE
Create AutoConfiguration for PostgremML

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-ai#242]

**Comment by usrivastava92** [comment]
@markpollack The PR is ready for review, Is there anything additional I should address aside from adhering to the checklist outlined in the pull request?

**Comment by markpollack** [comment]
@usrivastava92 It does not appear that you made a PR from your branch.  Can you please do that?

Thanks

**Comment by markpollack** [comment]
Apologies, I somehow missed the PR.  We will merge it. Thanks.

**Comment by markpollack** [comment]
fixed in 5718f9683d4abd0702cfe99d754558f01996fec0
