### ISSUE TITLE
OpenAI example for 0.8.0-SNAPSHOT is out of date

### ISSUE THREAD

**Issue by krushnatkhawale** [spring-projects/spring-ai#245]
Greetings!!!

In [Spring-AI documentation](https://docs.spring.io/spring-ai/reference/getting-started.html) for version 0.8.0-SNAPSHOT, the OpenAI example project is out of date. The [example project was developed for version 0.2.0-SNAPSHOT](https://github.com/rd-1-2022/ai-openai-helloworld/blob/51f73f71b09f0a2cb7b5f09cce100e086bfde18d/pom.xml#L33) and not compatible with 0.8.0-SNAPSHOT because the class ```org.springframework.ai.client.AiClient``` is replaced by ```org.springframework.ai.chat.ChatClient```.

Need link to example project which is using version 0.8.0-SNAPSHOT.

**Comment by markpollack** [comment]
I will create a high level issue to update the various places that older snapshot are being used and link to this one. 

I think that the documentation you are referring to has already been updated to reflect the changes going to 0.8.0-SNAPSHOT.

https://docs.spring.io/spring-ai/reference/api/clients/openai.html#_getting_started

I will close the issue for now, please reopen if you feel something has not been addressed.

Thanks!
