### ISSUE TITLE
[Ollama] Missing metadata for nested configuration properties

### ISSUE THREAD

**Issue by ThomasVitale** [spring-projects/spring-ai#246]
**Bug description**
When using the Ollama Spring Boot Starter dependency, the nested properties within `OllamaChatProperties` and `OllamaEmbeddingProperties` mapped to the `OllamaOptions` class are missing the necessary metadata to be recognised by IDEs and the GraalVM compiler.

**Environment**
Spring AI: 0.8.0-SNAPSHOT
Java: 21
Dependency: `org.springframework.ai:spring-ai-ollama-spring-boot-starter`

**Expected behavior**
Nested properties must be included when generating metadata for the custom configuration properties in the Ollama starter dependency. 

The `@NestedConfigurationProperty` annotation can be used to solve both the problem with IDEs and with the GraalVM native compilation, as explained in the Spring Boot documentation [here](https://docs.spring.io/spring-boot/docs/3.2.1/reference/htmlsingle/#appendix.configuration-metadata.annotation-processor.automatic-metadata-generation.nested-properties) and [here](https://docs.spring.io/spring-boot/docs/3.2.1/reference/htmlsingle/#native-image.advanced.nested-configuration-properties).

**Comment by markpollack** [comment]
Good catch, and a bit embarrassed. :smiley:  Will address here and in other autoconfiguration classes.  

Thanks!

**Comment by ThomasVitale** [comment]
Thank you!
