### ISSUE TITLE
Elastic/OpenSearch DB vector

### ISSUE THREAD

**Issue by williamspindox** [spring-projects/spring-ai#257]
Hi, can you implement elasticsearch/opensearch vector db support?
And then add some code examples of course :)
Thanks

**Comment by markpollack** [comment]
This has been contributed as part of https://github.com/spring-projects/spring-ai/pull/234  Please check it out.  We would welcome contributions of additional example code.

**Comment by JM-Lab** [comment]
https://github.com/spring-projects/spring-ai/pull/508 opensearch vector db support

**Comment by ThomasVitale** [comment]
Both implementations are part of Spring AI now:

* ElasticSearch: https://docs.spring.io/spring-ai/reference/api/vectordbs/elasticsearch.html
* OpenSearch: https://docs.spring.io/spring-ai/reference/api/vectordbs/opensearch.html

**Comment by markpollack** [comment]
Has been added.
