### ISSUE TITLE
Microsoft Entra authentication

### ISSUE THREAD

**Issue by williamspindox** [spring-projects/spring-ai#260]
Please add Microsoft Entra authentication for Azure:
https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#authentication

**Comment by markpollack** [comment]
Thanks, we will look into this.

**Comment by williamspindox** [comment]
I'm trying something like this:

AzureProfile azureProfile = new AzureProfile(AzureEnvironment.AZURE);
TokenCredential tokenCredential = new ClientSecretCredentialBuilder()
	.clientId("xxxxxxxxxxxxxxxxx")
	.clientSecret("xxxxxxxxxxxxxxxxx")
	.tenantId("xxxxxxxxxxxxxxxxx")
	.authorityHost(azureProfile.getEnvironment().getActiveDirectoryEndpoint())
	.build();
return new OpenAIClientBuilder().endpoint(connectionProperties.getEndpoint())
	.credential(tokenCredential)
	.buildClient();

but I get:

Azure Identity => ERROR in getToken() call for scopes [https://cognitiveservices.azure.com/.default]: java.util.concurrent.ExecutionException: com.microsoft.aad.msal4j.MsalClientException: java.io.UncheckedIOException: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem

(already tried to import some cert)

**Comment by williamspindox** [comment]
When will it be available on your release? Thank you

**Comment by markpollack** [comment]
also see https://github.com/spring-projects/spring-ai/issues/309

**Comment by williamspindox** [comment]
https://github.com/spring-projects/spring-ai/pull/448

**Comment by markpollack** [comment]
I will ask someone from microsoft to review this, I am not able to easily evaluate what is going on here.  Sorry it is taking a while.

**Comment by williamspindox** [comment]
No problem. I've already tested my PR with the Entra authentication on Azure and it works great, but welcome a check by someone from Microsoft. Regards.
