### ISSUE TITLE
Update samples in docs, spring-cli projects, and AI workshop code to use version 0.8.1

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-ai#262]
There are various places with sample code that needs to be updated.  Known places are

- [x] reference documentation
- [x] Azure AI Workshop
- [x] Sample Carnia RAG search application

**Comment by bertilmuth** [comment]
Since I tried to use it, failed and had to adapt it anyway, I can provide an update to the example in:
[Open AI - Getting Started](https://docs.spring.io/spring-ai/reference/api/clients/openai.html#_getting_started)

If you want that, which format is best? Pull request?

**Comment by emileastih1** [comment]
Hello,
I tried to use this section of the documentation [OpenAI Manual Configuration](https://docs.spring.io/spring-ai/reference/api/embeddings/openai-embeddings.html#_manual_configuration) to manual configure the OpenAI embedding client by creating an instance of OpenAiEmbeddingClient but it is not working.
The ".withDefaultOptions" method is not present on the OpenAiEmbeddingClient class.
I ended up doing the following to make it work: 
```var openAiApi = new OpenAiApi(openaiApiKey);
        return new OpenAiEmbeddingClient(
                openAiApi,
                MetadataMode.EMBED,
                OpenAiEmbeddingOptions.builder().withModel(OpenAiApi.DEFAULT_EMBEDDING_MODEL).build(),
                RetryUtils.DEFAULT_RETRY_TEMPLATE);```

**Comment by markpollack** [comment]
https://github.com/spring-projects/spring-ai/issues/447   and thanks @emileastih1
