### ISSUE TITLE
Support async client

### ISSUE THREAD

**Issue by liemng** [spring-projects/spring-ai#283]
**Expected Behavior**

Support reactive model with OpenAI, such as https://learn.microsoft.com/en-us/java/api/com.azure.ai.openai.openaiasyncclient?view=azure-java-preview

**Current Behavior**

Currently, OpenAI calls are blocking.

**Context**

We currently have a webflux application using Azure OpenAI; mixing async and sync is not ideal.

**Comment by tzolov** [comment]
@liemng have you checked all the chat clients implementing the [StreamingModelClient.java](https://github.com/spring-projects/spring-ai/blob/main/spring-ai-core/src/main/java/org/springframework/ai/model/StreamingModelClient.java)?
Like: 
- `OpenAiChatClient#stream((Prompt prompt): Flux<ChatResponse>`
-  `OllamaChatClient#stream((Prompt prompt): Flux<ChatResponse>`
-  `BedrockTitanChatClient#stream((Prompt prompt): Flux<ChatResponse>`
- `BedrockLlama2ChatClient#stream((Prompt prompt): Flux<ChatResponse>`
- `BedrockCohereChatClient#stream((Prompt prompt): Flux<ChatResponse>`
- `BedrockAnthropicChatClient#stream((Prompt prompt): Flux<ChatResponse>`
- `AzureOpenAiChatClient#stream((Prompt prompt): Flux<ChatResponse>`

All of those implement the streaming chat response provided from the underlying models and return a reactive `Flux<ChatResponse>`.

You can check the various test for an examples how to use it.

**Comment by markpollack** [comment]
Closing as the classes listed support async functionality.

**Comment by liemng** [comment]
@markpollack , Sorry for responding late... California outage :(

Streaming is different than non-blocking I/O.  What I am referring to is non-streaming, non-blocking requests like: https://learn.microsoft.com/en-us/java/api/com.azure.ai.openai.openaiasyncclient?view=azure-java-preview#com-azure-ai-openai-openaiasyncclient-getchatcompletions(java-lang-string-com-azure-ai-openai-models-chatcompletionsoptions). 

Is there plan to support non-streaming, non-blocking I/O?

**Comment by XhstormR** [comment]
Yes, We need support for async APIs that can return `Mono<ChatResponse>` .

**Comment by johnidm** [comment]
Recently, I worked on a project at my job where I needed to execute a batch of requests to OpenAI simultaneously and retrieve the results in order.

I found a way to achieve this using WebFlux - [WebFluxController](https://github.com/johnidm/youtube-videos-code-examples/blob/main/spring-boot-ai-threading/src/main/java/com/example/spring_boot_ai_threading/controllers/WebFluxController.java)

However, my goal was to use Spring AI to avoid writing extra code. I was able to accomplish this using the Stream API - [SpringAIController](
https://github.com/johnidm/youtube-videos-code-examples/blob/main/spring-boot-ai-threading/src/main/java/com/example/spring_boot_ai_threading/controllers/SpringAIController.java)

Both solutions are very fast. The request shown [here](https://github.com/johnidm/youtube-videos-code-examples/blob/main/spring-boot-ai-threading/README.md#springai-request-example) is executed in both approaches in just 3 seconds.
