### ISSUE TITLE
Missing OpenAiImageClient spring boot auto-configuration.

### ISSUE THREAD

**Issue by tzolov** [spring-projects/spring-ai#289]
The OpenAiImageClient doesn't provide boot auto-configuration.

**Comment by ThomasVitale** [comment]
@tzolov if needed, I'm available to work on this

**Comment by tzolov** [comment]
@ThomasVitale any help is welcome. Thank you.

**Comment by ThomasVitale** [comment]
@tzolov I have opened a PR with the changes to add OpenAiImageClient auto-configuration: https://github.com/spring-projects/spring-ai/pull/292
