### ISSUE TITLE
spring ai dependencies how to use in gradle kotlin, doc does not say this

### ISSUE THREAD

**Issue by nagkumar** [spring-projects/spring-ai#290]
```
  <repositories>
    <repository>
      <id>spring-snapshots</id>
      <name>Spring Snapshots</name>
      <url>https://repo.spring.io/snapshot</url>
      <releases>
        <enabled>false</enabled>
      </releases>
    </repository>
  </repositories>
```

Can you pl share the best way to use spring ai project in gradle kts file.. releases and enabled does not seem to exist in gradle

tried these 
<img width="457" alt="image" src="https://github.com/spring-projects/spring-ai/assets/332234/820451cb-8ddd-4de6-9c81-69da14543321"> and

<img width="627" alt="image" src="https://github.com/spring-projects/spring-ai/assets/332234/7ae92acb-6e36-4fb2-9c9a-5adbb250bfd3">

but gives error

<img width="1176" alt="image" src="https://github.com/spring-projects/spring-ai/assets/332234/a342a743-16e9-4a69-b402-b8c8af12a09e">

**Comment by ThomasVitale** [comment]
@nagkumar it looks like a typo in the artifact group. It should be `org.springframework.ai` and not `org.springframework.boot`:

```groovy
repositories {
    mavenCentral()
    maven { url 'https://repo.spring.io/milestone' }
    maven { url 'https://repo.spring.io/snapshot' }
}

dependencies {
    implementation "org.springframework.ai:spring-ai-openai-spring-boot-starter:0.8.0-SNAPSHOT"
}
```

**Comment by markpollack** [comment]
There is now a common getting started section, that show how to add the bom dependency for both maven and gradle. 

See https://docs.spring.io/spring-ai/reference/getting-started.html

For each chatclient and embeddingclient, their section in the documentation shows the dependencies to add for autoconfiguration and for manual configuration for both maven and gradle.  For example, see openai [autoconfiguration docs](https://docs.spring.io/spring-ai/reference/api/clients/openai-chat.html#_auto_configuration)  and [manual configuration docs](https://docs.spring.io/spring-ai/reference/api/clients/openai-chat.html#_manual_configuration).

The vector database deps aren't yet in the same format/structure.


Closing the issue for now.  If there are any other omissions in the docs, feel free to raise a new issue and/or PR.
