### ISSUE TITLE
Dev Services with Testcontainers and Docker Compose

### ISSUE THREAD

**Issue by ThomasVitale** [spring-projects/spring-ai#312]
A nice feature to improve the developer experience with Spring AI would be to have some autoconfiguration for running Ollama and vector stores as containers, either with Testcontainers or Docker Compose.

Do you envision such support to be part of the Spring AI project? If so, I'm available to contribute a pull request and introduce a `spring-ai-testcontainers` and `spring-ai-docker-compose` modules. Perhaps, starting with Ollama and Chroma support to have examples of both a model provider and a vector store.

**Comment by eddumelendez** [comment]
Hey @ThomasVitale! pretty cool that we thought the same 😄 . See https://github.com/spring-projects/spring-ai/issues/151

**Comment by ThomasVitale** [comment]
@eddumelendez I hadn't seen that issue, thanks for mentioning it :) I'll close this one as duplicate
