### ISSUE TITLE
Add vector data upload log

### ISSUE THREAD

**Issue by DanilTk** [spring-projects/spring-ai#315]
Hi,

While uploading a book onto vector db, it would be good to have an option to turn on status log saying how many docs processed/left to process as at some point i just thought nothing really happens, but in fact the program was still processing 100 pages pdf

**Comment by markpollack** [comment]
So adding a debug log inside the loop [here](https://github.com/spring-projects/spring-ai/blob/5552a118aaeb69f8bbfdbd9c87d22c53254c2769/document-readers/pdf-reader/src/main/java/org/springframework/ai/reader/pdf/PagePdfDocumentReader.java#L103)?

**Comment by markpollack** [comment]
I've added some logging, up to a max of 10 log statements in the PDF reader.  Reopen if this is not what you were expecting.

See 7b893410573184df4a1f8ff4f28525670d0b11ef
