### ISSUE TITLE
FunctionMessage Incorrect message type

### ISSUE THREAD

**Issue by PabloSanchi** [spring-projects/spring-ai#324]
**Bug description**
FunctionMessage class has a `SYSTEM` message type.
```java
public class FunctionMessage extends AbstractMessage {
	public FunctionMessage(String content) {
		super(MessageType.SYSTEM, content);
}
```
Class located: `spring-ai/spring-ai-core/src/main/java/org/springframework/ai/chat/messages/FunctionMessage.java`

**Minimal Complete Reproducible example**

```java
protected String messageToString(Message message) {
      switch (message.getMessageType()) {
	      case SYSTEM:
		      return message.getContent();
	      case USER:
		      return humanPrompt + " " + message.getContent();
	      case ASSISTANT:
		      return assistantPrompt + " " + message.getContent();
	      case FUNCTION:
		      throw new IllegalArgumentException("Tool execution results are not supported for Bedrock models");
      }
      
      throw new IllegalArgumentException("Unknown message type: " + message.getMessageType());
}
```
This snippet will not throw the following exception `IllegalArgumentException("Tool execution results are not supported for Bedrock models");` for `FunctionMessage` messages as the type is marked as `SYSTEM` and not `FUNCTION`

The code is located: `/spring-ai/models/spring-ai-bedrock/src/main/java/org/springframework/ai/bedrock/MessageToPromptConverter.java`

**Comment by tzolov** [comment]
Good catch @PabloSanchi !

Apparently the FUNCTION message type is not used currently.  It is not used in our  [OpenAI Function Calling](https://docs.spring.io/spring-ai/reference/api/clients/functions/openai-chat-functions.html) impl. either.
We shall see if this message type is ever required as we progress implementing function calling for other models. 

In the meantime if fix the inconsistency.
