### ISSUE TITLE
Review Neo4j documentation and the Auto-configuration implementation

### ISSUE THREAD

**Issue by tzolov** [spring-projects/spring-ai#329]
* Review the https://docs.spring.io/spring-ai/reference/api/vectordbs/neo4j.html documentation.
Source: https://github.com/spring-projects/spring-ai/blob/main/spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/neo4j.adoc

* Review the neo4j boot auto-configuration: https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/vectorstore/neo4j 
Shouldn't we consider using the existing [Neo4j boot starter and auto-conf](https://github.com/spring-projects/spring-boot/tree/v3.2.2/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/neo4j) instead of re-implementing the driver configuration again?

**Comment by meistermeier** [comment]
I think going with an "optional driver configuration" section and explaining that otherwise the auto-configured bean will be used is the way to go. There is already no _need_ to configure it manually. Will do this.

**Comment by tzolov** [comment]
Resolved with ffcb84e
