### ISSUE TITLE
qdrant vector store support

### ISSUE THREAD

**Issue by radhakrishna67** [spring-projects/spring-ai#331]
**Expected Behavior**

Qdrant vector database is not currently supported by Spring AI

**Current Behavior**

Qdrant vector database support along with all other vector stores as its benmarking is out performs all others.

**Context**
We are using Qdrant vector store to have all the embeddings stored, indexed and searched out of it.
So we would like Sping AI to support it.

**Comment by Anush008** [comment]
Hi @radhakrishna67. I'll try to contribute this feature.

**Comment by tzolov** [comment]
@Anush008 this will be appreciated!
