### ISSUE TITLE
Implement Bedrock Jurassic ChatClient

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-ai#343]
note, it does not support streaming.

**Comment by hemeda3** [comment]
Hi @markpollack  I want to work on this

**Comment by hemeda3** [comment]
Here is the PR:
https://github.com/spring-projects/spring-ai/pull/384

**Comment by tzolov** [comment]
Resolved with #384 and committed at c036931065730619a9fb01c90fbe63d7ffbccb1d
