### ISSUE TITLE
spring-ai-starter-stability-ai is not managed in the BOM

### ISSUE THREAD

**Issue by mhalbritter** [spring-projects/spring-ai#348]
Hello!

The [stability-ai-starter](https://github.com/spring-projects/spring-ai/blob/main/spring-ai-spring-boot-starters/spring-ai-starter-stability-ai/pom.xml) is not managed in the BOM.

I think that's an oversight.

**Comment by markpollack** [comment]
I've added it in 14e4a6cccf6027ab1499f2f6b6240096213c8808
