### ISSUE TITLE
Artifactory - Bad header value content-type of pom.xml from repo.spring.io/artifactory/snapshot

### ISSUE THREAD

**Issue by Amine-Kadi** [spring-projects/spring-ai#349]
We opened an issue [1] on Spring Framework repository and we were informed that it's specifically related to Spring AI project.
[1] https://github.com/spring-projects/spring-framework/issues/32304

What was in the issue :

We are not able to download pom.xml files from the snapshot repository of repo.spring.io with our updated 'Sonatype Nexus Repository' due to an invalid header value for content-type returned by Artifactory.

2024-02-14 06:46:54,705+0000 WARN [xxx] UNKNOWN org.sonatype.nexus.repository.storage.StorageTxImpl - An exception occurred determining the content type of asset org/springframework/ai/spring-ai-openai-spring-boot-starter/0.8.0-SNAPSHOT/spring-ai-openai-spring-boot-starter-0.8.0-20240214.061929-153.pom in repository maven_proxy_repo.spring.io-snapshot

2024-02-14 06:46:54,708+0000 WARN [xxx] UNKNOWN org.sonatype.nexus.repository.view.handlers.ExceptionHandler - Invalid content: GET /org/springframework/ai/spring-ai-openai-spring-boot-starter/0.8.0-SNAPSHOT/spring-ai-openai-spring-boot-starter-0.8.0-20240214.061929-153.pom: org.sonatype.nexus.repository.InvalidContentException: Content type could not be determined: application/x-maven-pom xml

curl -L -v "https://repo.spring.io/artifactory/snapshot/org/springframework/ai/spring-ai-openai-spring-boot-starter/0.8.0-SNAPSHOT/spring-ai-openai-spring-boot-starter-0.8.0-20240220.195606-169.pom" > /dev/null
< "content-type: application/x-maven-pom xml"

Note that there is a space in the value. According to RFC, that is not legal: https://www.w3.org/Protocols/rfc1341/4_Content-Type.html

According to Nexus Documentation, the correct value could be "content-type: application/x-maven-pom"

Since the header value does not respect the RFC, we cannot override configuration of our Nexus Repository to accept a such mime-type value

The milestone repository (https://repo.spring.io/artifactory/milestone/) send a valid header value "content-type: application/x-maven-pom+xml" according to the RFC

For more investigation, we tested a couple of artifact to see if it happens on all Spring AI artifact, or just few of them.
It seems that all the pom served by AmazonS3 tends to have this content-type.
As there is a follox-redirect when accessing via jfrog, the content-type is present in the URL as a query param, so the + is replaced by a Space.

What should be done is encode the param response-content-type so it appears as following : ?response-content-type=application/x-maven-pom%2Bxml

**Comment by greggy-laloutre** [comment]
I just saw spring-ai:0.8.0 has been published on Milestone repository with the same error.

**Comment by jvalkeal** [comment]
As you've probably noticed from request logs the trouble comes from cloudflare which acts as a cdn frontend. We're investigating why this only affects `spring-ai` artifacts as rest of the spring umbrella looks to be fine.

**Comment by jvalkeal** [comment]
@greggy-laloutre We changed cdn settings. Can you try again.

**Comment by greggy-laloutre** [comment]
Hello, headers looks great for Snapshot and Milestone ! 
Thanks for the update of your CDN.
I'm currently in vacation, so I'll ask to my colleague to validate our Nexus connection to your repository.

**Comment by markpollack** [comment]
Closing the issue, reopen if you still get errors.
