### ISSUE TITLE
SearchRequest.withFilterExpression(String textExpression) errors when metadata field name has "_"

### ISSUE THREAD

**Issue by xiaonan2323** [spring-projects/spring-ai#356]
We are trying to implement searchRequest and set filter expression by using `SearchRequest.withFilterExpression(String textExpression)`. However, the metadata field name we used has "_"(underscore) and it results in the error like this:
<img width="376" alt="image" src="https://github.com/spring-projects/spring-ai/assets/124708046/07e13800-5ae8-42c5-aacb-afa476b9d358">
Error example is:
`searchRequest.withFilterExpression("country_code == 'UK'");`

 We tried to use `Filter.Expression expression` instead of plain string and it does work. Example is:
`searchRequest.withFilterExpression(new FilterExpressionBuilder().eq("country_code", "UK").build());`
However, we need to build a more complex query that can't be implemented with the current collection of `ExpressionType`(Filter expression operations).

**Comment by markpollack** [comment]
Can you add single quotes around country_code, eg. `searchRequest.withFilterExpression(" 'country_code' == 'UK'");

**Comment by xiaonan2323** [comment]
Adding single quotes around field name fixed it, thank you.
