### ISSUE TITLE
Add ETL diagram to documentation

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-ai#374]

**Comment by tzolov** [comment]
@markpollack 
Added generic ETL diagram https://docs.spring.io/spring-ai/reference/0.8-SNAPSHOT/api/etl-pipeline.html#_api_overview
And detailed one at the bottom: https://docs.spring.io/spring-ai/reference/0.8-SNAPSHOT/api/etl-pipeline.html#etl-class-diagram

**Comment by tzolov** [comment]
Resolved
