### ISSUE TITLE
BedrockCohereEmbeddingOptions does not implement EmbeddingOptions

### ISSUE THREAD

**Issue by tzolov** [spring-projects/spring-ai#389]
### Discussed in https://github.com/spring-projects/spring-ai/discussions/381

<div type='discussions-op-text'>

<sup>Originally posted by **sharathcshekhar** March  1, 2024</sup>
In the documentation to use Cohere embeddings, https://docs.spring.io/spring-ai/reference/api/embeddings/bedrock-cohere-embedding.html#embedding-options, the below code example is provided.

```
EmbeddingResponse embeddingResponse = embeddingClient.call(
    new EmbeddingRequest(List.of("Hello World", "World is big and salvation is near"),
        BedrockCohereEmbeddingOptions.builder()
        	.withInputType(InputType.SEARCH_DOCUMENT)
        .build()));
```
But this code does not work because BedrockCohereEmbeddingOptions does not implement EmbeddingOptions. I am on 0.8.0. Is there something I am missing? Thanks.
</div>

**Comment by elviacis** [comment]
`https://docs.github.com/en/rest/about-the-rest-api/api-versions?apiVersion=2022-11-28 `
