### ISSUE TITLE
Add support Amazon Bedrock Claud 3.0

### ISSUE THREAD

**Issue by lameroot** [spring-projects/spring-ai#399]
Add support Amazon Bedrock Claud 3.0

**Comment by ben-gineer** [comment]
We need to add support for Claude's Messages API as a prerequisite. All previous Claude versions support this. See:

https://docs.anthropic.com/claude/reference/migrating-from-text-completions-to-messages

**Comment by ben-gineer** [comment]
Initial attempt over at https://github.com/spring-projects/spring-ai/pull/424

@tzolov - would you be able to comment on how we can incorporate support for the new Messages API? It's currently sitting in a new package, as the APIs are quite different.

The package name at least should change, as this isn't Claude 3 specific. I've tested on Instant, 2 and 3 models.

Thanks

**Comment by tzolov** [comment]
Resolved with #424
