### ISSUE TITLE
Redis Vector Sentinel Support

### ISSUE THREAD

**Issue by shannonantony** [spring-projects/spring-ai#438]
**Expected Behavior**

Need support to connect to multiple Redis sentinel nodes

**Current Behavior**

Currently, only one redis node connection is supported.

**Context**

**Comment by markpollack** [comment]
As the Redis support builds upon Spring Data and Spring Boot support for Redis, you can configure this using application configuration properties.  See https://dzone.com/articles/redis-sentinel-with-spring as a start.
