### ISSUE TITLE
Add documentation for the MongoDB Atlas Vector Store

### ISSUE THREAD

**Issue by tzolov** [spring-projects/spring-ai#456]
Consider extending the existing WIP: https://github.com/spring-projects/spring-ai/blob/main/spring-ai-docs/src/main/antora/modules/ROOT/pages/api/vectordbs/mongodb.adoc

**Comment by markpollack** [comment]
The prerequisite section is missing.  See https://docs.spring.io/spring-ai/reference/api/vectordbs/pinecone.html#_prerequisites for an example of hosted model docs.  Reaching out to mongodb contacts to see if they want to contribute.
