### ISSUE TITLE
Add Auto-configuration and Boot starter for the GemFire Vector Store

### ISSUE THREAD

**Issue by tzolov** [spring-projects/spring-ai#488]
GemFire Vector Store: https://github.com/spring-projects/spring-ai/tree/main/vector-stores/spring-ai-gemfire

- Make sure to register the AutoConfig class to the [org.springframework.boot.autoconfigure.AutoConfiguration.imports](https://github.com/spring-projects/spring-ai/blob/main/spring-ai-spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports)
- Add the boot-starter dependency to the [BOM](https://github.com/spring-projects/spring-ai/blob/main/spring-ai-bom/pom.xml).

**Comment by eddumelendez** [comment]
I wonder if there is any chance to test it using Testcontainers [GemFire module](https://testcontainers.com/modules/gemfire/) and the [Docker image](https://network.tanzu.vmware.com/products/gemfire-vectordb), which is hosted in VMWare registry. [V2 was recently announced](https://gemfire.dev/blog/testing-spring-for-gemfire-apps-with-gemfire-testcontainers/)

**Comment by geetrawat** [comment]
> I wonder if there is any chance to test it using Testcontainers [GemFire module](https://testcontainers.com/modules/gemfire/) and the [Docker image](https://network.tanzu.vmware.com/products/gemfire-vectordb), which is hosted in VMWare registry. [V2 was recently announced](https://gemfire.dev/blog/testing-spring-for-gemfire-apps-with-gemfire-testcontainers/)

For now, we have  docker image to test the Gemfire vector store [https://hub.docker.com/r/gemfire/gemfire] but we don't yet support Testcontainers yet. Planning to add that in near future.

**Comment by tzolov** [comment]
@geetrawat, 

if not mistaken, the https://hub.docker.com/r/gemfire/gemfire image is only the plain GemFire, not the GemFire with the Vector Store extension? 

If so, IMO, it should be trivial to create a `Dockerfile` that starts from the existing Gemfire image, adds the necessary vector store extension files, configures them and then commits a new image that supports both?

This would definitely improve the testability for the store.

**Comment by izeye** [comment]
This seems to have been resolved via https://github.com/spring-projects/spring-ai/pull/599.

**Comment by markpollack** [comment]
yes indeed.  Closing now.
