### ISSUE TITLE
Improve customization of setting metadata in PDF Document Readers

### ISSUE THREAD

**Issue by iAMSagar44** [spring-projects/spring-ai#502]
### Discussed in https://github.com/spring-projects/spring-ai/discussions/501

<div type='discussions-op-text'>

<sup>Originally posted by **iAMSagar44** March 24, 2024</sup>
Currently the DocumentReader interface implementations (e.g.PagePdfDocumentReader) add the page number and file name to the metadata map. This eventually populates the 'metadata' column with the page number and file name.
I want to add more metadata information (for e.g. author) during the ETL process, so that I can then use these fields as metadata fields in the similarity search filters. I could not find any way to do this, apart from creating my own implementation of the DocumentReader interface.

Is there any other way to cater for this use case?</div>

**Comment by markpollack** [comment]
Hi.  You can update the metadata in the document after it is created by the PagePdfDocumentReader.  As an example, look at this [data loading application](https://github.com/spring-cli-projects/ai-azure-rag-load/blob/main/src/main/java/com/example/rag/DataLoadingJob.java), that applies the filename and the version to the document.

That said, the PagePdfDocumentReader should be more subclass friendly.  I will make a change for that.

**Comment by markpollack** [comment]
See https://github.com/spring-projects/spring-ai/pull/1093
