### ISSUE TITLE
docs: link is invailed.

### ISSUE THREAD

**Issue by yuluo-yx** [spring-projects/spring-ai#528]
https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-azure-openai/README.md:

![image](https://github.com/spring-projects/spring-ai/assets/77964041/9d431e7f-a1d2-4ac7-a58d-50d7f46c5dce)

![image](https://github.com/spring-projects/spring-ai/assets/77964041/12c6a01c-fec5-418c-8fb6-8a2965d7c644)

**Comment by tzolov** [comment]
Thank you for reporting this @yuluo-yx 
It should be resoled now.
