### ISSUE TITLE
[Malicious, Package Squatting Attack] Do Not Use Packages from the "io DOT springboot" domain!!!

### ISSUE THREAD

**Issue by yuluo-yx** [spring-projects/spring-ai#537]
hi, community. If I want to develop based on spring core module to adapt new ai big model, how pom.xml is selected.

Docs：

```xml
  <repositories>
    <repository>
      <id>spring-milestones</id>
      <name>Spring Milestones</name>
      <url>https://repo.spring.io/milestone</url>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <repository>
      <id>spring-snapshots</id>
      <name>Spring Snapshots</name>
      <url>https://repo.spring.io/snapshot</url>
      <releases>
        <enabled>false</enabled>
      </releases>
    </repository>
  </repositories>
```

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-bom</artifactId>
            <version>0.8.1-SNAPSHOT</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

Maven repo： https://mvnrepository.com/artifact/io DOT springboot DOT ai/spring-ai-core/1.0.0

```xml
<dependency>
    <groupId>io DOT springboot DOT ai</groupId>
    <artifactId>spring-ai-core</artifactId>
    <version>1.0.0</version>
</dependency>
```

Which one should I choose and is there any difference between them?

**Comment by yuluo-yx** [comment]
Community Issue Questions go unanswered?  There's already a backlog of questions.  @tzolov

**Comment by anbusampath** [comment]
> ```
> <dependencyManagement>
>     <dependencies>
>         <dependency>
>             <groupId>org.springframework.ai</groupId>
>             <artifactId>spring-ai-bom</artifactId>
>             <version>0.8.1-SNAPSHOT</version>
>             <type>pom</type>
>             <scope>import</scope>
>         </dependency>
>     </dependencies>
> </dependencyManagement>
> ```

you should continue to use above one.



> ```
> 
> <dependency>
>     <groupId>io.springboot.ai</groupId>
>     <artifactId>spring-ai-core</artifactId>
>     <version>1.0.0</version>
> </dependency>
> ```

This looks like some accidental publish.

**Comment by yuluo-yx** [comment]
> > ```
> > <dependencyManagement>
> >     <dependencies>
> >         <dependency>
> >             <groupId>org.springframework.ai</groupId>
> >             <artifactId>spring-ai-bom</artifactId>
> >             <version>0.8.1-SNAPSHOT</version>
> >             <type>pom</type>
> >             <scope>import</scope>
> >         </dependency>
> >     </dependencies>
> > </dependencyManagement>
> > ```
> 
> you should continue to use above one.
> 
> > ```
> > 
> > <dependency>
> >     <groupId>io.springboot.ai</groupId>
> >     <artifactId>spring-ai-core</artifactId>
> >     <version>1.0.0</version>
> > </dependency>
> > ```
> 
> This looks like some accidental publish.

got it, thanks

**Comment by tzolov** [comment]
@yuluo-yx , @anbusampath  

This looks like a package squatting attack!  

The io.springboot.ai is not a valid, likely malicious domain. 

The Spring domain is `org.springframework.ai`  and the latest version is `1.0.0-SNAPSHOT`:

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-bom</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

**Comment by tzolov** [comment]
And here is the official documentation with the currently supported versions and related docs: https://spring.io/projects/spring-ai#learn
Mind that `0.8.1` is a milestone (so not available on Maven Central).

**Comment by yuluo-yx** [comment]
> @yuluo-yx , @anbusampath
> 
> This looks like a package squatting attack!
> 
> The io.springboot.ai is not valid and likely malicious domain.
> 
> The official Spring domain is `org.springframework.ai` and the latest version is `1.0.0-SNAPSHOT`:
> 
> ```
> <dependencyManagement>
>     <dependencies>
>         <dependency>
>             <groupId>org.springframework.ai</groupId>
>             <artifactId>spring-ai-bom</artifactId>
>             <version>1.0.0-SNAPSHOT</version>
>             <type>pom</type>
>             <scope>import</scope>
>         </dependency>
>     </dependencies>
> </dependencyManagement>
> ```

got it. IMO, if indeed there is no relevant release. Something should be done officially, as the github address is the same as the project address, and some people may introduce the wrong package due to carelessness.

![1712543517626](https://github.com/spring-projects/spring-ai/assets/77964041/3ba2da6e-fe2b-4614-bf07-ecb209f4d365)

**Comment by XhstormR** [comment]
I also encountered this problem.  I was using the wrong dependency package 😂:
```
implementation("io.springboot.ai:spring-ai-azure-openai-spring-boot-starter:1.0.0")
```

**Comment by yuluo-yx** [comment]
> Thanks for raising this @yuluo-yx. We're not aware of it and will do our best to deal it. From what I can see the `springboot DOT io` is Chinese portal. Wonder how popular is it and if the owners are involved or at least aware of the attack.

![1712567919769](https://github.com/spring-projects/spring-ai/assets/77964041/12235009-e1aa-48aa-98e2-b01ad7cf989f)

Judging from the usage of the maven repository, there are still a lot of users. Also, the update is close to the time of the 1.0.0 release

**Comment by yuluo-yx** [comment]
> I also encountered this problem. I was using the wrong dependency package 😂:
> 
> ```
> // not official do not use
> implementation("io DOT springboot DOT ai:spring-ai-azure-openai-spring-boot-starter:1.0.0")
> ```

Haha, very unfortunate.

**Comment by digital-shokunin** [comment]
I'm no expert, but I see no evidence of anything malicious being added _yet_. Perhaps the idea was to sneak a benign change through and later make changes once that trust or namespace was established?

```
pkgdiff infiles/spring-ai-core-0.8.1.jar infiles/spring-ai-core-1.0.0.jar.zip 
reading packages ...
comparing packages ...
creating report ...
result: CHANGED (1.9%)
report: pkgdiff_reports/spring-ai-core/0.8.1_to_1.0.0.jar/changes_report.html
```

<img width="1102" alt="image" src="https://github.com/spring-projects/spring-ai/assets/913856/0ab2ca02-572e-4859-a76a-6f2a968da577">

<img width="1371" alt="image" src="https://github.com/spring-projects/spring-ai/assets/913856/f61d4640-3462-412d-adb9-ec4a39bc2907">

<img width="1342" alt="image" src="https://github.com/spring-projects/spring-ai/assets/913856/067a7f00-83fc-497b-b072-42491d33e1d8">

**Comment by digital-shokunin** [comment]
[pkgdiff_reports.zip](https://github.com/spring-projects/spring-ai/files/14910343/pkgdiff_reports.zip)

Copy of the report attached.

**Comment by konczdev** [comment]
The situation will only get worse. @tzolov 

![image](https://github.com/spring-projects/spring-ai/assets/128691423/b1802108-310e-476c-b0fe-7aa45dbd51f2)

**Comment by yuluo-yx** [comment]
> The situation will only get worse. @tzolov
> 
> ![image](https://private-user-images.githubusercontent.com/128691423/330901511-b1802108-310e-476c-b0fe-7aa45dbd51f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4NzEwODMsIm5iZiI6MTcxNTg3MDc4MywicGF0aCI6Ii8xMjg2OTE0MjMvMzMwOTAxNTExLWIxODAyMTA4LTMxMGUtNDc2Yy1iMGZlLTdhYTQ1ZGJkNTFmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQxNDQ2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjM5NWU2MDMwZjJhZDlkYzI5YjQ4NmU0OTQyMjIyZGQ3NDNmNzI5MDVlZmRhOWEzMmQ0MGM1NTRlYzUwYWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qQkyajHjKmnA7g-SUnpAhWXXz1jaUya6aZoWkw1w8pM)

It should be fixed soon, as the use of maven is increasing. 🤔

**Comment by dingmeng-xue** [comment]
@markpollack , FYI.

**Comment by markpollack** [comment]
The artifact is gone from Maven Central and the links from [mvnrepository.com](http://mvnrepository.com/) (if you try to click to download the pom or JAR) lead to 403s.
