### ISSUE TITLE
Should CassandraVectorStoreAutoConfiguration rely on CassandraAutoconfiguration?

### ISSUE THREAD

**Issue by eddumelendez** [spring-projects/spring-ai#576]
Please do a quick search on GitHub issues first, the feature you are about to request might have already been requested.

**Expected Behavior**
CassandraVectorStoreAutoConfiguration should rely on CassandraAutoconfiguration

**Current Behavior**
CqlSession is created on-the-fly duplicating CqlSession creation.

**Context**
CassandraVectorStore support was added in 656d238285838461d7f9f4ebc67fe1f8dc740750. I think it should be aligned with Neo4j and Elasticsearch to rely on existing Spring Boot autoconfiguration.

**Comment by tzolov** [comment]
@michaelsembwever , I think @eddumelendez  makes a good point. 
Existing [CassandraAutoConfiguration](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/cassandra/CassandraAutoConfiguration.html) provides the basics to setup connection. It also provides extensive list of [CassandraProperties](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/cassandra/CassandraProperties.html). 
For example you can check The PGVector (relying on JdbcTemplateAutoConfiguration), Neo4jVectorStoreAutoConfiguration on Neo4jAutoConfiguration, ElasticsearchVectorStoreAutoConfiguration on ElasticsearchRestClientAutoConfiguration and maybe more.

**Comment by michaelsembwever** [comment]
Thanks @eddumelendez 
I'm new to the autoconfigure, appreciate the quick feedback. Will get this fix today.

**Comment by michaelsembwever** [comment]
fixed in https://github.com/spring-projects/spring-ai/pull/575

**Comment by markpollack** [comment]
Thanks, we have been backlogged and getting around to this now.  Very much appreciate the PR

**Comment by eddumelendez** [comment]
This has been resolved via https://github.com/spring-projects/spring-ai/commit/0eaf7d05c9bc509f8ae2d9e16594ec2db4fd2b4a
