### ISSUE TITLE
Support hybrid search

### ISSUE THREAD

**Issue by impactCn** [spring-projects/spring-ai#579]
![image](https://github.com/spring-projects/spring-ai/assets/35489877/c760237f-ee29-4669-b074-88ba6ad96402)
During search, hybrid search, similar search and keyword search will be supported and submitted to LLM.

I am willing to submit this feature. Does the community have any better suggestions for my feature?

**Comment by markpollack** [comment]
We are working on this feature now in an Agent model.  It allows for multiple retrievers and then post processing those results.  I hope to have it released in the 1.0 M1 next week, if not by a M2 release.  Either way when there is a branch or PR to share, I’ll post back here.

**Comment by impactCn** [comment]
@markpollack Hi, I have implemented a hybrid search for PG that uses full-text retrieval and vector similarity. If the community needs me to implement it, I can submit it.

**Comment by alessiobertazzo88** [comment]
Hello everyone, I have also developed this feature that enables the user to define within the SearchRequest whether to use similarity search (vector-based, enabled by default), full-text search, or both (hybrid search). Additionally, it provides the possibility of using reranking approaches.

This implementation is applied to the vector store Azure SearchAI, and the implementation done by @impactCn can be seamlessly integrated as well.

The PR is #1227

**Comment by csterwa** [comment]
Duplicate.
