### ISSUE TITLE
Support function call in Bedrock Anthropic 3

### ISSUE THREAD

**Issue by lameroot** [spring-projects/spring-ai#587]
Could you add support functions call in Bedrock Anthropic 3?

**Comment by jledesma-opsguru** [comment]
@maxjiang153 Does SpringAI now support function call?

**Comment by maxjiang153** [comment]
@jledesma-opsguru I'm working on this, hopefully it will be finished in this week. https://github.com/spring-projects/spring-ai/pull/813
