### ISSUE TITLE
BedrockAnthropic3ChatClient returns ChatResponse without AnthropicUsage

### ISSUE THREAD

**Issue by lameroot** [spring-projects/spring-ai#600]
I'am using BedrockAnthropic3ChatClient and i can not get info about input and output tokens. But these parameters i can get from AnthropicChatResponse.

Could you transfer these parameters to ChatResponseMetadata ?

**Comment by tzolov** [comment]
This problem will resolved by the https://github.com/spring-projects/spring-ai/pull/605 indeed.

**Comment by markpollack** [comment]
closing as the PR has been merged
