### ISSUE TITLE
Function calling - FunctionCallingOptions doesn't work with OpenAiChatClient/AzureOpenAiChatClient

### ISSUE THREAD

**Issue by tha2015** [spring-projects/spring-ai#624]
**Bug description**
Function calling doesn't happen when using FunctionCallingOptions with OpenAiChatClient/AzureOpenAiChatClient

**Environment**
spring-ai-core-1.0.0-20240420.063719-118.jar
spring-ai-openai-1.0.0-20240420.063719-101.jar
spring-ai-azure-openai-1.0.0-20240420.063719-112.jar

**Steps to reproduce**

```kotlin
    // kotlin code
    val functionOptions = FunctionCallingOptions.builder()
        .withFunction("weatherFunction")
        .build()

    val response: ChatResponse = chatClient.call(
        Prompt(
            listOf(UserMessage("What's the weather like in San Francisco, Tokyo, and Paris?")),
            functionOptions
        )
    )

    println(response.result.output.content)
```

OpenAiChatClient:
```
Sorry, as an AI, I don't have real-time capabilities to provide current weather updates. Please check a reliable weather forecasting website or app for the most accurate and up-to-date information.
```

AzureOpenAiChatClient:
```
Sorry, as an AI, I don't have real-time capabilities to provide current weather updates. Please check a reliable weather forecasting website or app for this information.
```

**Expected behavior**
Function calling should happen and response should contain function call result.

**Analysis**
[AzureOpenAiChatClient.toAzureChatCompletionsOptions](https://github.com/spring-projects/spring-ai/blob/563f9b48af60a176b32ee4fa03877123f076b9a7/models/spring-ai-azure-openai/src/main/java/org/springframework/ai/azure/openai/AzureOpenAiChatClient.java#L177) and [OpenAiChatClient.createRequest](https://github.com/spring-projects/spring-ai/blob/563f9b48af60a176b32ee4fa03877123f076b9a7/models/spring-ai-openai/src/main/java/org/springframework/ai/openai/OpenAiChatClient.java#L243) don't use `FunctionCallingOptions.getFunctions()` for building the request,  so function call didn't happen.

**Comment by tzolov** [comment]
@tha2015 where is your `weatherFunction` defined? Not clear from your snippets above? 

As the documentation suggests you can [register your functions] as plain Function Bean or FunctionCallback wrapper.

Here is a working integration tests for FunctionCallback wrapper: [AzureOpenAiChatClientFunctionCallIT](https://github.com/spring-projects/spring-ai/blob/main/models/spring-ai-azure-openai/src/test/java/org/springframework/ai/azure/openai/function/AzureOpenAiChatClientFunctionCallIT.java).

And you can find more working ITs here: https://github.com/spring-projects/spring-ai/tree/main/spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/azure/tool

Let me know if this helps

**Comment by tzolov** [comment]
Also mind that the property `spring.ai.azure.openai.chat.options.model` has been renamed to `spring.ai.azure.openai.chat.options.deployment-name`.

**Comment by edumaxsantos** [comment]
I've been having the same issue with OpenAI. Just to test something, I copied OpenAiChatClient class and changed only one thing.

I actually didn't have the time to understand what is the purpose of IS_RUNTIME_CALL, although this tweak helped me make it work.
 
```java
if (this.defaultOptions != null) {
            // I removed '!' that was modifying IS_RUNTIME_CALL
            Set<String> defaultEnabledFunctions = this.handleFunctionCallbackConfigurations(this.defaultOptions,
                    IS_RUNTIME_CALL);

            functionsForThisRequest.addAll(defaultEnabledFunctions);

            request = ModelOptionsUtils.merge(request, this.defaultOptions, OpenAiApi.ChatCompletionRequest.class);
        }
```

**Comment by tha2015** [comment]
I could not setup the spring-ai project to run the tests, and when I copying the test to my project it failed. I'm attaching the screenshot of the code where it failed for your reference. My understanding is FunctionCallingOptions was handled like a normal ChatOptions (without `tools` property) and so the tools property was not used.
<img width="1005" alt="Screenshot 2024-05-01 at 9 02 47 AM" src="https://github.com/spring-projects/spring-ai/assets/15103994/07440d53-b55e-4a81-9ce5-79fc4595fb05">

**Comment by tha2015** [comment]
@tzolov I found out why the FunctionCallingOptions  IT test passed. It is because that test case [`functionCallWithPortableFunctionCallingOptions` ](https://github.com/spring-projects/spring-ai/blob/670bf8e2598226de6b338ac7fe672cea61785c7a/spring-ai-spring-boot-autoconfigure/src/test/java/org/springframework/ai/autoconfigure/openai/tool/FunctionCallbackWithPlainFunctionBeanIT.java#L87) doesn't have assertions like other test cases. I believe that if you add `assertThat(response.getResult().getOutput().getContent()).contains("30", "10", "15");` , the test will fail.
