### ISSUE TITLE
how to use in springboot2 project?

### ISSUE THREAD

**Issue by lishu2006ll** [spring-projects/spring-ai#629]
hello 
i have a springboot2 project, how to use it?

**Comment by ThomasVitale** [comment]
Spring Boot 2 reached end-of-life and is not supported anymore. Spring AI is built on top of Spring Boot 3.

You can find more information about which Spring Boot versions are currently supported here: https://spring.io/projects/spring-boot#support

**Comment by tzolov** [comment]
@lishu2006ll , indeed you need Spring Boot 3.2+

**Comment by tzolov** [comment]
Related to https://github.com/spring-projects/spring-ai/issues/574
