### ISSUE TITLE
spirng-ai-milvus default create index failed

### ISSUE THREAD

**Issue by imkratos** [spring-projects/spring-ai#630]
Please do a quick search on GitHub issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
when use milvus default create index ,  `io.milvus.exception.ServerException: index doesn't exist, collectionID 448783011129880848`

**Environment**
Please provide as many details as possible: Spring AI version, Java version, which vector store you use if any, etc

**Steps to reproduce**
Steps to reproduce the issue.

**Expected behavior**
<img width="802" alt="image" src="https://github.com/spring-projects/spring-ai/assets/3302461/33180121-bbb5-4a1b-9835-d993e87868f3">
without indexname ? 

**Minimal Complete Reproducible example**
Please provide a failing test or a minimal complete verifiable example that reproduces the issue.
Bug reports that are reproducible will take priority in resolution over reports that are not reproducible.

**Comment by markpollack** [comment]
See MilvusVectorStoreAutoConfigurationIT, it passes and creates the index at starutp.  You will find the code you attached in `MilvusVectorStore` and should set the property `initialize-schema` to `true`.  See the docs [here](https://docs.spring.io/spring-ai/reference/api/vectordbs/milvus.html#milvus-properties).

Please reopen with a
