### ISSUE TITLE
Ineffective OutputParser Implementation in PromptTemplate

### ISSUE THREAD

**Issue by alvaroblazmon** [spring-projects/spring-ai#661]
## Description
I have been testing the functionality of the `PromptTemplate` class and noticed that it includes a getter and a setter for an `OutputParser` variable. However, upon reviewing the code and conducting several tests, it appears that this variable is not being utilized as expected.

## Issue Details
The current implementation of `OutputParser` in `PromptTemplate` does not seem to affect the template output. Setting a value to `outputParser` does not integrate the parser's format into the template.

According to the documentation, the correct way to use an `OutputParser` in a `PromptTemplate` is by incorporating `{format}` in the template string, which should reflect the value from `outputParser.getFormat()` in the model.

## Proposals for Improvement
1. **Remove the `OutputParser`** from the `PromptTemplate` codebase to eliminate confusion, as it currently serves no operational purpose.
2. **Enhance `PromptTemplate`** by allowing `OutputParser` to be set either directly or through the constructor. The class should then automatically integrate the necessary format handling using `outputParser.getFormat()`.

## Steps to Reproduce
1. Instantiate a `PromptTemplate`.
2. Set a custom `OutputParser` with a specific format.
3. Generate output using the `PromptTemplate`.
4. Observe that the format specified in `OutputParser` is not reflected in the output.

**Comment by tha2015** [comment]
I have same concern about `PromptTemplate` when learning how to use it. There is no reason for including `outputParser` property into it and maybe it should be removed?

**Comment by markpollack** [comment]
I would be inclined to remove it.  This comes from the very early says where I was reviewing langchain and llamaindex and langchain had this design.  It is a mistake in retrospect.
