### ISSUE TITLE
move eager initialization of `PgVectorStore` from `afterPropertiesSet` to `ApplicationListener<ApplicationReadyEvent>`

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-ai#684]
at the moment there is initialization done on every run of `PgVectorStore`, which delays the startup time significantly. (more than double my normal startup time)

It would be good to: 

a) make this an opt-in, as it is in Spring Modulith, Spring Session, Spring Batch, Spring Integration, Spring Session, etc. 
b) move it to a later point in the Spring Boot application lifecycle, like `ApplicationListener<ApplicatinoReadyEvent>`, instead of `afterPropertiesReady`. this way, it'll happen _after_ the boot app has reported its startup time

**Comment by markpollack** [comment]
This was fixed with the introduction of `initialize-schema` true option recently merged
