### ISSUE TITLE
support spring boot's `ServiceConnection` mechanism

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-ai#685]
basically, spring boot can automatically during development create a connetion to a running docker image or to a testcontainer, allowing the user to avoid having to specify all this in `application.properties` during development. even better, the spring initializr can generate docker `compose.yml` definintiions and Testcontainers definitions for tests that point to a docker image. the result is the user goes to start.spring.io, chooses, eg, PgVectorDB, and one or both of Testcontainers or Docker Compose, and they get a `compose.yml` and Testcontainers tests ready to go. Even better, whrn they run their spring boot app they don't need to specify connectivity credentials in `application.properties`.

**Comment by eddumelendez** [comment]
Hi Josh, Testcontainers Service Connection support is already there for Ollama, ChromaDB, Milvus, Qdrant and Weaviate. See https://docs.spring.io/spring-ai/reference/1.0-SNAPSHOT/api/testcontainers.html#_service_connections

**Comment by eddumelendez** [comment]
For Docker Compose, see #733

**Comment by eddumelendez** [comment]
This can be closed now that Testcontainers and Docker Compose are supported. BTW, the support for those will come to start.spring.io in this [PR](https://github.com/spring-io/start.spring.io/pull/1484). PgVector and Neo4j are already supported.

**Comment by markpollack** [comment]
Thanks for the contribution @eddumelendez !!
