### ISSUE TITLE
Chromadb initialization permission error

### ISSUE THREAD

**Issue by superDSB** [spring-projects/spring-ai#691]
The location of password uses username.
 org.springframework.ai.chroma.ChromaApi#withBasicAuthCredentials
`public ChromaApi withBasicAuthCredentials(String username, String password) {`
`		this.restTemplate.getInterceptors().add(new BasicAuthenticationInterceptor(username, username));`
`		return this;`
`	}`

**Comment by eddumelendez** [comment]
Fixed via #713
