### ISSUE TITLE
About Ollama 

### ISSUE THREAD

**Issue by SimpleYj** [spring-projects/spring-ai#693]
Please do a quick search on GitHub issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
![14211715134529_ pic](https://github.com/spring-projects/spring-ai/assets/38721053/448e6dc4-aa2d-4a63-9a6a-1baf879f7e26)
![14201715134464_ pic](https://github.com/spring-projects/spring-ai/assets/38721053/9bc39cd3-332c-4a2a-b6ab-6b0c31311f2d)

**Environment**
Please provide as many details as possible: Spring AI version, Java version, which vector store you use if any, etc
Spring AI version :0.8.1
Spring AI :jdk17

**Steps to reproduce**
Steps to reproduce the issue.

**Expected behavior**

The Ollama is deployed on the server, and it can be tested successfully with curl, but when called using SpringAI configuration, a timeout error is reported. Occasionally, Interestingly, under certain conditions，it also works correctly.

**Minimal Complete Reproducible example**
Please provide a failing test or a minimal complete verifiable example that reproduces the issue.
Bug reports that are reproducible will take priority in resolution over reports that are not reproducible.

**Comment by dashaun** [comment]
@SimpleYj Can you please try again using 1.0.0-M1 and the latest version of Ollama.

You might have run into an Ollama issue. Ollama couldn't handle multiple requests at the same time, until recently.

**Comment by markpollack** [comment]
closing as there isn't enough info to resolve.
