### ISSUE TITLE
Can not get the usage info when using AzureOpenAiChatClient with stream() method

### ISSUE THREAD

**Issue by Showjib3** [spring-projects/spring-ai#694]
I'am trying to use AzureOpenAiChatClient.
When I'am using the stream() method, I can not get info about input and output tokens. It seems all is 0. But i can get from the callI() method.

**Comment by markpollack** [comment]
Thanks, will investigate.

**Comment by markpollack** [comment]
We have revamped the streaming support in M3, please take a look and see if it fixes the issue for you.  I believe it hsould.  Reopen if there is an issue.

**Comment by markpollack** [comment]
Here is a recent community discussion on this topic.  It isn't supported in the microsoft SDK, so until it is made available, there isn't anything we can do here.  https://learn.microsoft.com/en-us/answers/questions/1805363/azure-openai-streaming-token-usage

**Comment by Showjib3** [comment]
Ok, thank you 发自我的 iPhone在 2024年10月7日，23:24，Mark Pollack ***@***.***> 写道：﻿
Here is a recent community discussion on this topic.  It isn't supported in the microsoft SDK, so until it is made available, there isn't anything we can do here.  https://learn.microsoft.com/en-us/answers/questions/1805363/azure-openai-streaming-token-usage
