### ISSUE TITLE
Support Oracle 23ai as vector database

### ISSUE THREAD

**Issue by aalmiray** [spring-projects/spring-ai#703]
**Expected Behavior**

Oracle 23ai added vector as datatype, it also includes vector search algorithms.

**Context**

Oracle 23ai is available for free at https://www.oracle.com/database/free
Docker images can be found at https://github.com/gvenzl/oci-oracle-free

**Comment by elkana** [comment]
Try this https://github.com/elkana/spring-ai-oracle-rag.git

**Comment by fmeheust** [comment]
@elkana, I was going to start working on an implementation of a VectorStore using Oracle 23ai, but I see that you have already done it. Are you planning to contribute your code to Spring AI ?

**Comment by elkana** [comment]
> @elkana, I was going to start working on an implementation of a VectorStore using Oracle 23ai, but I see that you have already done it. Are you planning to contribute your code to Spring AI ?

Sorry, not that i know of. Please keep up the good work.

**Comment by loiclefevre** [comment]
Well, here we are... 🚀
