### ISSUE TITLE
Add comment and prevent IndexOutOfBounds exception in ImageResponse

### ISSUE THREAD

**Issue by devholic22** [spring-projects/spring-ai#706]
**Expected Behavior**

Previously, an `IndexOutOfBounds` exception might occur if the developer using the `getResult` function, I modified returns null. (if `imageGenerations` is empty)

**Current Behavior**

In this version, the `getResult` function returns index element number 0 of `imageGenerations` directly.

**Context**

- I added comments to make it easier to understand. (I referred to `ChatResponse`.)
- I modified to return null if `imageGenerations` is empty.
- I modified `toString` like `ChatResponse` format.

please see #745

**Comment by markpollack** [comment]
Thanks, closing as the fix was merged.
