### ISSUE TITLE
Reconsider the Type float/Float in the API

### ISSUE THREAD

**Issue by ullenboom** [spring-projects/spring-ai#712]
A floating-point number with limited precision is commonly used in AI. However, using `float` or `Float` as a data type in the API might be impractical, and it could be worth reevaluating this decision.

For instance, your own example in the reference documentation (https://docs.spring.io/spring-ai/reference/api/clients/ollama-chat.html) results in a compiler error, guess why :)

```
ChatResponse response = chatClient.call(
    new Prompt(
        "Generate the names of 5 famous pirates.",
        OllamaOptions.create()
            .withModel("llama2")
            .withTemperature(0.4)
    ));
```

**Comment by ThomasVitale** [comment]
It would be nice to use `Double` instead of `Float` in all the `ModelOptions` implementations. It would make the API more convenient to work with and the code more readable.

**Comment by markpollack** [comment]
I agree, thanks for raising the issue.  I will aim to fix this for the M2 release that is coming up shortly.

**Comment by csterwa** [comment]
@markpollack should this be moved to next milestone or release candidate?

**Comment by ThomasVitale** [comment]
I'm available to submit a PR on this. I had already done some preliminary analysis when working on the observability features. I should have the PR ready by the end of this week.

**Comment by ThomasVitale** [comment]
The PR is ready for review: https://github.com/spring-projects/spring-ai/pull/1325
