### ISSUE TITLE
Support JSON Type Detection for Parsing Arrays and Objects

### ISSUE THREAD

**Issue by rivkode** [spring-projects/spring-ai#749]
**Expected Behavior**

The JSON data should be correctly read and parsed regardless of whether it is an array or an object. The implementation should check the type of the root node and handle it accordingly. For instance, if the JSON data is an array, it should be read into a List<Map<String, Object>>. If it is an object, it should be processed as a single Map<String, Object>

// Todo
1. ~~Modifying Json objects
The objects you've added are all objects with a depth of 1.
I will modify the Json objects a bit more, so that the test case works with different types of objects.~~ Done

2. Look at how other open source Json readers are using it(ex [springboot JsonReader](https://github.com/spring-projects/spring-boot/blob/ba9708d7545eae70b851f0bfccf7b4cb685d6e75/spring-boot-project/spring-boot-tools/spring-boot-configuration-metadata/src/main/java/org/springframework/boot/configurationmetadata/JsonReader.java)), and reference on this.

**Current Behavior**

Currently, the code assumes that the JSON data is always in array format and tries to read it into a List<Map<String, Object>>. This causes failures when the JSON data is an object, as the current implementation does not handle this case.

**Context**

- JSON Type Check: The current implementation does not check whether the JSON data is an array or an object, leading to potential failures. The modified code uses JsonNode to inspect the type of the root node.
- ObjectMapper Reuse: The code reuses the ObjectMapper instance for reading and converting JSON data.
- Stream API: When the JSON data is an array, the modified code uses the Stream API to traverse the JsonNode, parse each node, convert it to a Document object, and collect these objects into a list.
- Type Conversion: The modified code uses the ObjectMapper's convertValue method to convert JsonNode to Map<String, Object>.

Please see as below
* #750

**Comment by markpollack** [comment]
Thanks for the PR.  Will get it into M2

**Comment by csterwa** [comment]
Closed as merged
