### ISSUE TITLE
PDFReader Test `doesNotContains` -> `contain` and Replace `Collectors.joining()` to `String.join()`

### ISSUE THREAD

**Issue by rivkode** [spring-projects/spring-ai#753]
**Expected Behavior**

- Using of `assertThat().doesNotContain() `-> `assertThat().contains()` may be passed for the test.
- ~~Using of `String.join()` may be for readability and simplicity.~~

When I looked at the other codes, most of them were using Collectors.joining(), with one exception. (`RedisFilterExpressionConverter`)
So I will change the modification to String.join() back to Collectors.joining().
If you think I should change it to String.join(), please comment and I will change it.

**Current Behavior**

I was wondering in the pdf file there was text `page 1 of 4, page of 2 of 4 ...` but why using doesNotContain() for the same text?
(If I misunderstand I will change it.)

~~I changed it to `String.join` because I don't think we need the extra stream operation for the simple joining of strings of text in a PDF file.
(If it is necessary,  I will change it.)~~

**Context**

- I modified`doesNotContain()` to `contain`. Then the test will be a success.
- ~~I modified `Collectors.joining()` to `String.join()`.~~

Please see PR as below.
* #754

![image](https://github.com/spring-projects/spring-ai/assets/109144975/8ac50eba-3973-4472-a284-f37db5f4a77a)

![image](https://github.com/spring-projects/spring-ai/assets/109144975/2bfcfbd7-6c29-46eb-95a7-b9af79410367)

![image](https://github.com/spring-projects/spring-ai/assets/109144975/87a7fab4-f778-4113-b3fa-bf42ff8c3922)

**Comment by markpollack** [comment]
Appreciate the efforts @rivkode Closing the issue now.
