### ISSUE TITLE
Add comment in OpenAiImageModel and modify RetryTemplate access level in OpenAiChatModel

### ISSUE THREAD

**Issue by devholic22** [spring-projects/spring-ai#755]
**Expected Behavior**

* before this version, `OpenAiImageModel` doesn't contains enough comments.
* and `OpenAiChatModel` RetryTemplate access level is `public`, I think it should change to `private`.

**Current Behavior**

**Context**
* add enough comment in `OpenAiImageModel` like `OpenAiChatModel` format.
* changed `public` to `private` in `OpenAiChatModel` RetryTemplate.

please see #756

**Comment by ThomasVitale** [comment]
@devholic22 I can see the PR has been merged. Can this issue be closed? https://github.com/spring-projects/spring-ai/pull/756
