### ISSUE TITLE
Index 0 out of bounds for length 0 exception in BedrockAnthropic3ChatModel

### ISSUE THREAD

**Issue by ShaunDeng** [spring-projects/spring-ai#757]
**Bug description**
Some models like BedrockAnthropic3 support stopSequences parameter, while the completions meet that token it will stop to generate. So there's a change to make model not generate anything. For example, we pass the prompt as 'Hi' and set stopSequences  to 'Hello', that probably make model not generate anything.

**Environment**
Spring AI 1.0.0-SNAPSHOT, Java 17

**Steps to reproduce**
<img width="937" alt="BedrockAnthropic3ChatModelIssue" src="https://github.com/spring-projects/spring-ai/assets/16474510/ab388447-1899-46f5-a6f1-a799e8c085fd">

**Expected behavior**
Since 1.0.0-SNAPSHOT is not stable, this case serves as a reminder in case you incorporate the following code snippet into the stable version.
···
return new ChatResponse(List.of(new Generation(((Anthropic3ChatBedrockApi.MediaContent)response.content().get(0)).text())));
···

**Comment by maxjiang153** [comment]
Hi @ShaunDeng could you provide a demo to reproduce this issue?

**Comment by ShaunDeng** [comment]
Hi @maxjiang153 , as I post at the above, just set the prompt as 'hi', and set the model stopSequences to 'Hello' or 'hi' to reproduce

**Comment by csterwa** [comment]
Closed as merged.
