### ISSUE TITLE
Refactor FunctionCallbackContext to FuctionCallBackResolver interface

### ISSUE THREAD

**Issue by konczdev** [spring-projects/spring-ai#758]
**Expected Behavior**

Introducing `FucntionCallBackResolver` would enable more flexibility and control over how to add [FunctionCallbacks](https://github.com/spring-projects/spring-ai/blob/main/spring-ai-core/src/main/java/org/springframework/ai/model/function/FunctionCallback.java) to a request.

```
public interface FunctionCallBackResolver {

	public FunctionCallback getFunctionCallback(@NonNull String beanName, @Nullable String defaultDescription);
}
```
```
public class ApplicationContextFunctionCallbackResolver implements FunctionCallBackResolver, ApplicationContextAware {

    //the current implementation of FunctionCallbackContext 

}
```

**Current Behavior**

There are 2 options now how to add [FunctionCallbacks](https://github.com/spring-projects/spring-ai/blob/main/spring-ai-core/src/main/java/org/springframework/ai/model/function/FunctionCallback.java) to a Request

- manually register with [FunctionCallingOptions](https://github.com/spring-projects/spring-ai/blob/main/spring-ai-core/src/main/java/org/springframework/ai/model/function/FunctionCallingOptions.java)
- automatically resolved from the ApplicationContext using the [FunctionCallbackContext](https://github.com/spring-projects/spring-ai/blob/main/spring-ai-core/src/main/java/org/springframework/ai/model/function/FunctionCallbackContext.java)

**Context**

What are you trying to accomplish?

- Custom logic for dynamic function resolution

What other alternatives have you considered?
Are you aware of any workarounds?
- Making some less elegant logic around prompt options building.

**Comment by tzolov** [comment]
Hi @konczdev, 

Usually the `FunctionCallbackContext` instance is created in the auto-configuration for each Chat Model using the `@ConditionalOnMissingBean` annotation. For example this is the [OpenAI Auto-Config FunctionCallbackContext](https://github.com/spring-projects/spring-ai/blob/f9a9c02e2b07a4b192c7e1c7f8229347e8556975/spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/openai/OpenAiAutoConfiguration.java#L259).

So I presume that you can extend the FunctionCallbackContext with your own version that overrides the resolver method and expose it as a Bean in your spring configuration?  Wouldn't this work?

**Comment by konczdev** [comment]
Sorry, I had to stop experimenting with the project due to a serious health issue. However, I looked at the PR now and this is exactly what I had in my mind.
