### ISSUE TITLE
Redis Vector Search is returning only 10 results

### ISSUE THREAD

**Issue by shannonantony** [spring-projects/spring-ai#765]
Hi,

I am testing Sprint AI with Redis Vector store to house my documents. However, when I perform Similarity query, I am getting only maximum of 10 results from redis.

Do I need to set any paramater to get more results?

appreciate your help

thanks

Jay

**Comment by alexcheng1982** [comment]
When creating `SearchRequest`, you can use `withTopK` to specify the maximum number of results.

**Comment by markpollack** [comment]
closing, please reopen if this did not solve your problem
