### ISSUE TITLE
[BUG]The request body format for the ZhiPuAiEmbeddingModel.call method is incorrect

### ISSUE THREAD

**Issue by wb04307201** [spring-projects/spring-ai#771]
when invoke ZhiPuAiEmbeddingModel.call method, I get some error,like this  
![image](https://github.com/spring-projects/spring-ai/assets/35208417/cee15bd9-0da6-4a00-a421-9264bca2e648)  

then I check ZhiPuAiEmbeddingModel class and ZhiPuAi website  
![image](https://github.com/spring-projects/spring-ai/assets/35208417/4d432713-090d-4b13-9765-303999f62219)
![image](https://github.com/spring-projects/spring-ai/assets/35208417/c6a0decf-32d1-4ca4-9a28-eab3bc9dec4a)

in ZhiPuAiEmbeddingModel class use a Collection, but in website input is String  

Should convert the org.springframework.ai.embedding.EmbeddingRequest class to a generic type to adapt to this situation?

**Comment by mxsl-gr** [comment]
fixed on PR #773
