### ISSUE TITLE
odd issue creating embeddings with Ollama

### ISSUE THREAD

**Issue by joshlong** [spring-projects/spring-ai#840]
Hi, I am trying to use the Ollama `EmbeddingModel` with `PgVectorStore` and it's failing with 

```
Caused by: org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [CREATE INDEX IF NOT EXISTS spring_ai_vector_index ON vector_store USING HNSW (embedding vector_cosine_ops)
]; SQL state [XX000]; error code [0]; ERROR: column cannot have more than 2000 dimensions for hnsw index
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1549) ~[spring-jdbc-6.1.8.jar:6
```

the same application works with OpenAI 

here's a sample https://github.com/joshlong/bootiful-spring-boot-2024/tree/main/service

and there's a PgVector Docker Compose file here https://github.com/joshlong/bootiful-spring-boot-2024/blob/main/compose.yaml

help, please

**Comment by ThomasVitale** [comment]
@joshlong unfortunately, Ollama has a fixed 4096 size for the embeddings and it's not currently possible to customise the value. There is a feature request to do that: https://github.com/ollama/ollama/issues/651

I have opened a PR to improve the Spring AI PGvector documentation and mention the limitation of the HNSW indexing strategy, which can't support dimensionality above 2000: https://github.com/spring-projects/spring-ai/pull/825/files

My current workaround to get applications running fully locally is to use Ollama for the chat model and one of the ONXX Transformers for the embedding model: https://docs.spring.io/spring-ai/reference/api/embeddings/onnx.html 

I hope Ollama addresses this issue asap!

**Comment by markpollack** [comment]
Thanks @ThomasVitale Closing the issue

**Comment by ThomasVitale** [comment]
In case it's useful to people landing on this issue and having the same problem, I'll share another tip to use Ollama for embeddings paired with PGVector.

The multi-purpose models in the Ollama library (like `mistral` and `llama3.1`) seem to have been configured with 4096 dimensionality, which cannot be changed as of now, and doesn't work with PGVector.

However, dedicated embedding models like `nomic-embed-text` (full list here: https://ollama.com/search?q=&c=embedding) are configured with different dimensionality. In many cases, it's lower than 2000, so they all can be used with PGVector (and Spring AI lets you configure the dimensions via `spring.ai.vectorstore.pgvector.dimensions`).

**Comment by smitchell** [comment]
@joshlong  - I did "ollama pull all-minim" the used this in my properties file:

```
  ai:
    ollama:
      base-url: http://${OLLAMA_HOST}:11434
      chat:
        model: llama3.1:8b
      embedding:
        enabled: true
        model: all-minilm
```

You can find the code here: https://github.com/ByteworksHomeLab/spring-ai-lab

**Comment by joshlong** [comment]
Thanks all

**Comment by Hyun-June-Choi** [comment]
> 이 문제에 직면해 같은 문제를 겪고 있는 사람들에게 유용할 경우, PGVector와 함께 Ollama를 임베딩에 사용하는 또 다른 팁을 알려드리겠습니다.
> 
> Ollama 라이브러리의 다목적 모델( `mistral`및 `llama3.1`)은 4096차원으로 구성된 것으로 보이며, 현재로서는 이를 변경할 수 없고 PGVector와 작동하지 않습니다.
> 
> 그러나 `nomic-embed-text`(전체 목록은 여기: https://ollama.com/search?q=&c=embedding )과 같은 전용 임베딩 모델은 다른 차원으로 구성됩니다. 많은 경우 2000보다 낮으므로 모두 PGVector와 함께 사용할 수 있습니다(그리고 Spring AI는 를 통해 차원을 구성할 수 있습니다 `spring.ai.vectorstore.pgvector.dimensions`).



> In case it's useful to people landing on this issue and having the same problem, I'll share another tip to use Ollama for embeddings paired with PGVector.
> 
> The multi-purpose models in the Ollama library (like `mistral` and `llama3.1`) seem to have been configured with 4096 dimensionality, which cannot be changed as of now, and doesn't work with PGVector.
> 
> However, dedicated embedding models like `nomic-embed-text` (full list here: https://ollama.com/search?q=&c=embedding) are configured with different dimensionality. In many cases, it's lower than 2000, so they all can be used with PGVector (and Spring AI lets you configure the dimensions via `spring.ai.vectorstore.pgvector.dimensions`).

@joshlong 

like below? 

ai:
    ollama:
      base-url: http://${OLLAMA_HOST}:11434
      chat:
        model: llama3.1:8b
      embedding:
        enabled: true
        model: nomic-embed-text
