### ISSUE TITLE
Exact similarity match with Redis Vector Store always retuning empty list

### ISSUE THREAD

**Issue by siddharth223437** [spring-projects/spring-ai#845]
Please do a quick search on GitHub issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
Exact similarity match with Redis Vector Store always retuning empty list

**Environment**
Spring AI version: 1.0.0-SNAPSHOT, 
Java version: 17, 
which vector store you use: Redis Vector Store

**Steps to reproduce**
```
FilterExpressionBuilder b = new FilterExpressionBuilder();
		SearchRequest searchRequest = SearchRequest
				.query("find by id").withFilterExpression(b.eq("id",303).build());
		List<Document> documents = vectorStore.similaritySearch(searchRequest);
```

**Expected behavior**
vectorStore.similaritySearch should return one record

**Comment by markpollack** [comment]
Is `"find by id"` something that is the document, can you provide a more complete example?

**Comment by cxlet** [comment]
Same problem

public List<Document> getDocuments() {
        FilterExpressionBuilder b = new FilterExpressionBuilder();
        SearchRequest searchRequest = SearchRequest.builder()
                // .query("技术")
                .filterExpression(
                        // b.eq("ossObjectName", this.ossObjectName)
                        b.eq("test1", "test1")
                                .build())
                .build();
        log.debug("getDocuments:{}", searchRequest);
        return vectorStore.similaritySearch(searchRequest);
    }

**Comment by KyleUltimate** [comment]
got the same issue
