### ISSUE TITLE
OpenAi audio models are not conditional

### ISSUE THREAD

**Issue by RikJux** [spring-projects/spring-ai#848]
Inside the **OpenAiAutoConfiguration** class, the ***OpenAiAudioTranscriptionModel*** and ***OpenAiAudioSpeechModel*** beans are not conditional on properties as the other models (****OpenAiChatModel, OpenAiEmbeddingModel, OpenAiImageModel****)

**Comment by markpollack** [comment]
Thanks for reporting this.

**Comment by sobychacko** [comment]
@RikJux The `@ConditionalOnProperty` annotation has already been applied to those beans. It looks like that may have been the case when you created this issue (on the snapshot version). 

https://github.com/spring-projects/spring-ai/blob/main/spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/openai/OpenAiAutoConfiguration.java#L169

https://github.com/spring-projects/spring-ai/blob/main/spring-ai-spring-boot-autoconfigure/src/main/java/org/springframework/ai/autoconfigure/openai/OpenAiAutoConfiguration.java#L196

Closing the issue. Please feel free to re-open if you still see any problems. Thanks!
