### ISSUE TITLE
Advanced RAG Component Support

### ISSUE THREAD

**Issue by Joker1212** [spring-projects/spring-ai#851]
is there a plan for "Advanced RAG Component Support"?
such as "Semantic Chunking", "Reranker Model" etc..

**Comment by markpollack** [comment]
yes, we are looking into this. There are other issues under the RAG label that duplicate this request.

**Comment by fedecompa** [comment]
Why is this issue closed? There is no open issue on advanced chunking strategies ( like "semantic chunking" for example) and spring AI does not support that up to now.

**Comment by fedecompa** [comment]
@markpollack Why was this issue closed as completed? There is no open issue regarding advanced chunking strategies like 'semantic chunking' or 'dynamic section retrieval', and up to now, neither Spring AI nor langchain4j supports them.

**Comment by SlaouiSS** [comment]
This is still a relevant gap for RAG pipelines.

I've been working on open-source implementations addressing some of these components:

Semantic chunking: SlaouiSS/semantic-chunker
Hybrid retrieval: SlaouiSS/spring-ai-hybrid-retriever

The semantic chunker is built around embeddings and semantic similarity to determine chunk boundaries, while the hybrid retriever combines multiple retrieval strategies.

These experiments made me think that both could potentially fit naturally into Spring AI's existing RAG abstractions.

I'd be happy to contribute or discuss what native Spring AI APIs for these components could look like.
