### ISSUE TITLE
has error  multiple modal calling in zhipuAi

### ISSUE THREAD

**Issue by viewhang** [spring-projects/spring-ai#854]
**Bug description**
zhipu  multiple modal api doc 
<img width="1000" alt="image" src="https://github.com/spring-projects/spring-ai/assets/26957298/336b384a-f11a-4fb6-8f0e-e0f6e930bdc7">

The `image_url. url ` here can be a base64 string but should not include the prefix like this `data:image/png;base64,`
<img width="594" alt="image" src="https://github.com/spring-projects/spring-ai/assets/26957298/280fbea7-f810-441d-8a62-3fbab039a078">

**Environment**
 Spring AI version：
```
 <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-zhipuai-spring-boot-starter</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
```
 Java version：17

**Steps to reproduce**

```
final Media recourceMedia = new Media(MimeTypeUtils.IMAGE_PNG, new FileSystemResource(imageFile));
        String content = chatClient.prompt()
                .user(userSpec -> userSpec
                        .text(message)
                        .media(recourceMedia)
                )
                .call()
                .content();
```
return 
```
org.springframework.ai.retry.NonTransientAiException: 400 - {"error":{"code":"1210","message":"图片输入格式/解析错误"}}
```

**Expected behavior**
request success 

**Minimal Complete Reproducible example**
see  **Steps to reproduce**

**Comment by mxsl-gr** [comment]
hi, I haven't added multi-modal (GLM-4V) support yet. i will take a look at this issue later.

**Comment by mxsl-gr** [comment]
i have add multi-model support in PR #859

**Comment by mxsl-gr** [comment]
@viewhang hi, i noticed the PR has been merged, you can pull the code and give it try 😊

**Comment by viewhang** [comment]
it works well Thanks
