### ISSUE TITLE
openAI call issue

### ISSUE THREAD

**Issue by qq1005894049** [spring-projects/spring-ai#856]
Using
[OpenAiChatModel OpenAiChatModel] Calling the openAI dialogue, the parameters used in the call do not match the official open AI documentation
Spring AI generates parameter formats:
{
"Messages":[
{
"Content":[
{
"Type": "text",
"Text": "Who are you?"
}
],
"Role": "user"
}
],
"Model": "Qwen1.5-72B Chat GPTQ Int4",
"Stream": false,
"Temperature": 0.7
}

OpenAi officially requires parameter format:
{
"Model": "Qwen1.5-72B Chat GPTQ Int4",
"Messages":[
{
"Role": "User",
"Hello"
}
]
}

**Comment by tzolov** [comment]
Resolved by a6bed95358ab2cd5a3b3ec9a1a614a1b7ae610aa
