### ISSUE TITLE
Opensearch similarity search should include index name

### ISSUE THREAD

**Issue by quachc** [spring-projects/spring-ai#885]
**Bug description**
`SearchRequest` does not include index name which results in an error when using Opensearch role `own_index`:
*no permissions for [indices:data/read/search] and User [name=...]*

**Environment**
Spring AI 1.0.0-SNAPSHOT
Java 21,
Opensearch 2.14.0

**Steps to reproduce**
Create an user with permissions for a single index (e.g. role `own_index`)

**Expected behavior**
Should be able to execute the similarity search without errors

**Minimal Complete Reproducible example**
Not available...

**Comment by inpink** [comment]
I have addressed this issue in the submitted PR #1435. I kindly request your review of the changes. Thank you! 😊
