### ISSUE TITLE
Create an AbstractChatModel class that adds logging of request and response.

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-ai#909]
debug log level should be sufficient.  This needs to occur in a few places, in particular in the case of Flux, see `DefaultCallPromptResponseSpec.doGetChatResponse` and `DefaultStreamPromptResponseSpec.doGetFluxChatResponse` for implementation hints.

Change `OpenAiChatModel` to inherit from this abstract base class.  Once that is reviewed and discussed, we can have a separate PR that would change all the other implementations of `ChatModel` to extend `AbstractChatModel`

**Comment by ThomasVitale** [comment]
I shared a few thoughts about this in https://github.com/spring-projects/spring-ai/issues/512#issuecomment-2185096414
