### ISSUE TITLE
The company has deployed a large open source model and provided an http interface. Now how can I use Spring AI to access the http interface of the private model?

### ISSUE THREAD

**Issue by haibucuoba** [spring-projects/spring-ai#916]
The company has deployed a large open source model and provided an http interface. Now how can I use Spring AI to access the http interface of the private model?

**Comment by mxsl-gr** [comment]
do you know the standard for the model http api? if it compatible with OpenAI, you can use the `OpenAI` configuration directly and just config the base-url.

**Comment by csterwa** [comment]
Please review documentation for setting base URL: https://docs.spring.io/spring-ai/reference/api/chat/groq-chat.html
