### ISSUE TITLE
Remove PaLM Model support as it is deprecated and will be decomissioned

### ISSUE THREAD

**Issue by markpollack** [spring-projects/spring-ai#924]
See https://ai.google.dev/palm_docs/deprecation

The API will be decommissioned in Auguest 15th, so there is no point in keeping it in Spring AI as we will be post 1.0 GA by then.

**Comment by ddobrin** [comment]
PaLM2 support will end in Oct 2024, and can be removed
https://ai.google.dev/palm_docs/palm

**Comment by markpollack** [comment]
remember to remove documentation as well.
