### ISSUE TITLE
Provide Anthropic Claude streaming Function Calling support

### ISSUE THREAD

**Issue by tzolov** [spring-projects/spring-ai#930]
Currently provide Anthropic support only non-streaming function calling. 
Extend the support for streaming similar to OpenAI, MistralAI, Gemini and Azure OpenAI.

**Comment by tzolov** [comment]
Fyi @Grogdunn , @didalgolab 
as you've done some related work, you may find it interested to explore this as well.

**Comment by didalgolab** [comment]
@tzolov I'm going to look into this.
