### ISSUE TITLE
Add comment in OpenAiAudioSpeechModel and remove duplicated comment in OpenAiAudioSpeechOptions

### ISSUE THREAD

**Issue by devholic22** [spring-projects/spring-ai#931]
* I found that `OpenAiAudioSpeechModel` doesn’t have enough comments for better understanding the code. 
* I found a duplicated comment in `OpenAiAudioSpeechOptions` (about `AudioResponseFormat`).

please see #932

**Comment by ThomasVitale** [comment]
@devholic22 I can see that https://github.com/spring-projects/spring-ai/pull/932 got merged. Can this issue be closed?
