### ISSUE TITLE
OpenAiChatModel NullPointerException

### ISSUE THREAD

**Issue by chj9** [spring-projects/spring-ai#970]
Please do a quick search on GitHub issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
![image](https://github.com/spring-projects/spring-ai/assets/16426260/d95f083d-4ae8-41ab-ad25-1c890040cd6e)
![image](https://github.com/spring-projects/spring-ai/assets/16426260/08f3b5b7-c680-410b-8554-9a10fa1dce40)
org.springframework.ai.openai.OpenAiChatModel#stream

when roleMap is Empty throw NullPointerException

**Comment by devholic22** [comment]
@chj9 I think it can be solve by ternary operator, and if roleMap has a key with id, we can put that value in it, and if not, we can save null. What do you think? If you think this is right, it would be nice for me to do it.

**Comment by chj9** [comment]
> @chj9 I think it can be solve by ternary operator, and if roleMap has a key with id, we can put that value in it, and if not, we can save null. What do you think? If you think this is right, it would be nice for me to do it.

yes, of course，but if you still use the `Map.of` function method can not save null ，this is my code inherited from the OpenAiChatModel class to make changes, and now it is running fine
![image](https://github.com/spring-projects/spring-ai/assets/16426260/cb05e14c-19f4-4669-ba1a-4b5aec9209bf)

**Comment by devholic22** [comment]
@chj9 thank you for sharing your code. Additionally, it looks like from Java 8 you can write getOrDefault on the Map interface. How about this?
```java
Map.of("id", id, "role", roleMap.getOrDefault(id, ""), "finishReason", finish));
```

**Comment by devholic22** [comment]
> @chj9 thank you for sharing your code. Additionally, it looks like from Java 8 you can write `getOrDefault` on the Map interface. How about this?
> 
> ```java
> Map.of("id", id, "role", roleMap.getOrDefault(id, ""), "finishReason", finish));
> ```

if you agree, I'll make PR for fix this issue.

**Comment by chj9** [comment]
Agreed. Very good

> > @chj9 thank you for sharing your code. Additionally, it looks like from Java 8 you can write `getOrDefault` on the Map interface. How about this?
> > ```java
> > Map.of("id", id, "role", roleMap.getOrDefault(id, ""), "finishReason", finish));
> > ```
> 
> if you agree, I'll make PR for fix this issue.

agreed. very good!

**Comment by tzolov** [comment]
@chj9 thank you for catching this issue
