### ISSUE TITLE
minmax stream output failed

### ISSUE THREAD

**Issue by syzpig** [spring-projects/spring-ai#984]
**Bug description**
minmax: The stream output kept returning FluxMap, and the stream output failed

**Environment**
Please provide as many details as possible: Spring AI version, Java version, which vector store you use if any, etc

**Steps to reproduce**
Steps to reproduce the issue.

**Expected behavior**
流式输出

**Minimal Complete Reproducible example**
Please provide a failing test or a minimal complete verifiable example that reproduces the issue.
Bug reports that are reproducible will take priority in resolution over reports that are not reproducible.

**Comment by mxsl-gr** [comment]
do you have any information, like code or error log?

**Comment by xieyucan** [comment]
The framework itself should not have any issues; I have successfully invoked both the chat clients and chat models for ZhiPu and MiniMax locally.
If needed, I can provide you with the basic code as a reference.

**Comment by Admin-ppq** [comment]
> 框架本身应该没什么问题，我已经在本地成功调用了 ZhiPu 和 MiniMax 的聊天客户端和聊天模型， 如果需要的话，我可以给你提供基本代码供参考。
你好，可以帮我提供一下参考吗，非常感谢

**Comment by csterwa** [comment]
@syzpig do you have any more details or need for this issue? Will close but please reopen if there is more to discuss.
