### ISSUE TITLE
多个starter同时引用，出现问题，没有设置实例化优先级

### ISSUE THREAD

**Issue by syzpig** [spring-projects/spring-ai#99]
Please do a quick search on Github issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
![image](https://github.com/spring-projects-experimental/spring-ai/assets/28538048/6e3303a6-8bb3-45df-b73f-54fcb2b1308e)

**Environment**
Please provide as many details as possible: Spring AI version, Java version, which vector store you use if any, etc

**Steps to reproduce**
Steps to reproduce the issue.

**Expected behavior**

**Minimal Complete Reproducible example**
Please provide a failing test or a minimal complete verifiable example that reproduces the issue.
Bug reports that are reproducible will take priority in resolution over reports that are not reproducible.

**Comment by markpollack** [comment]
I am not sure how you got this error, it would seem like you included two autoconfigurations in your application.  That results in two instances of AiClient.  In this case, you should disable autoconfiguration and create the AiClient implementations yourself with appropriate qualifiers.

**Comment by markpollack** [comment]
Please reopen the issue if this did not solve your concern.
