### ISSUE TITLE
Add documentation how to use the OpenAI model client to access Groq inference engine. 

### ISSUE THREAD

**Issue by tzolov** [spring-projects/spring-ai#996]
The [Groq API](https://console.groq.com/docs/api-reference#chat-create) provides high level of compatibility with the OpenAI API.
The existing Spring AI OpenAI model client can be used to access the Groq inference API for most chat completion tasks. 
Provide documentation and instructions how to re-use the OpenAI Model Client for accessing the Groq chat completion endpoint.

**Comment by tzolov** [comment]
Resolved by d8be884cb1ed09e1e949a544ec3f9844d4d3a976

**Comment by KotlinFactory** [comment]
Also how to access multiple inference engines at once

**Comment by tzolov** [comment]
@KotlinFactory can you please elaborate, what you mean by "multiple inference engines"? 

Do you mean multiple Groq models or perhaps multiple Models across different providers? 

Also can you provide some use cases to support such setup?
